### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by rogersgj** [photopea/UTIF.js#1]
Hello, would it be possible to show a working example of this?  Does it work on MultiPage tiff images too?

**Comment by photopea** [comment]
Hi, I have added an example code. It does support MultiPage images, too. Let me know if you have any problems.

**Comment by photopea** [comment]
So does it work?

**Comment by rogersgj** [comment]
No I can't get it to work.  Sorry it took me so long to get back to you.  I don't know if I am basing it too much off of what I did with tiff.js.  I am very interested in an alternate.  I didn't have much luck with tiff.js with large docs in IE.  This is the code I am using, very simple:

<!doctype html>
<html>
  <head>
    <title>tiff.js demo</title>
  </head>
  <body>
    <script src="./jquery-1.10.1.min.js"></script>
    <script src="./UTIF.js"></script>
    <script type="text/javascript">

		
function imgLoaded(buff) {
  var pages = UTIF.decode(buff);   
  var rgba  = UTIF.toRGBA8(pages[0]);  // Uint8Array with RGBA pixels
  console.log(pages[0].width, pages[0].height, pages[0]);
}

var xhr = new XMLHttpRequest();
xhr.open("GET", "small.tif");
xhr.responseType = "arraybuffer";
xhr.onload = imgLoaded;   xhr.send();

    </script>
  </body>
</html>

I get the error:  Uncaught TypeError: Cannot read property '0' of undefined
    at Object.UTIF.decode (UTIF.js:60)
    at XMLHttpRequest.imgLoaded (basic.html:13)
UTIF.decode @ UTIF.js:60
imgLoaded @ basic.html:13

**Comment by photopea** [comment]
That looks like your file does not have the width defined. Can you send me your TIFF file (e.g. to support@photopea.com) ?  Does it open in www.Photopea.com ?

**Comment by rogersgj** [comment]
When I use tiff.js it does come back with a width defined if that helps.  But no, it doesn't open on photopea.com.  I figured it was due to the multipage, that is why I asked originally.  Will put up a image in the next few minutes.

**Comment by photopea** [comment]
Did you really see the error? Because in my case, the computation ends up in an infinite loop.

BTW I already know what is a problem and I will fix it asap.

**Comment by rogersgj** [comment]
I see the error when I try to load the tiff from the page I created from your code.  I do not see the error on photopea.com, the page just locks up on me.  

Thank you for looking into the issue.

**Comment by rogersgj** [comment]
Actually, I tried building the page with the tiff image you supplied (and worked) with Photopea.com.  It didn't work either and I got the same error.  So I am assuming in addition I am doing something else wrong with the page.  Here is a screen shot:
![screen shot 2017-04-12 at 12 00 27 pm](https://cloud.githubusercontent.com/assets/26065376/24967404/fa6f6d12-1f77-11e7-89c0-471359176413.png)
What am I doing wrong?

**Comment by photopea** [comment]
The file that you sent me has a name "DH5F.TIF"

**Comment by rogersgj** [comment]
Yes it does.  I was attempting to get it to work with the tiff file you
posted.

From my mobile, please excuse errors or grammatical mistakes...

**Comment by photopea** [comment]
I am very sorry. I wrote the code of an example without a proper testing. Please use the new example code. Now, you will be able to load G4.TIF.  Soon, I will fix the rest, so you can load DH5F.TIF too.

**Comment by rogersgj** [comment]
No need to be sorry.  Thanks for the updated code, but now I am getting a different error.  I am sorry for being a pain.  Now I am getting the error:

UTIF.js:7 Uncaught TypeError: Cannot read property 'width' of undefined
    at Object.UTIF.toRGBA8 (UTIF.js:7)
    at XMLHttpRequest.imgLoaded (basic.html:14)
UTIF.toRGBA8	@	UTIF.js:7
imgLoaded	@	basic.html:14

**Comment by photopea** [comment]
I updated the UTIF.js library few days ago, try to update it too :)

**Comment by photopea** [comment]
The problem was in my implementation of Fax compression, which could not deal with black pixels on the left edge. I managed to fix it and you can successfully parse your file now (try it in Photopea). Please use the latest example code and the latest JS file.

I am confident enough to close this issue. Let me know if you have any other problems :)

**Comment by rogersgj** [comment]
Awesome!  Works great on photopea.com!  Now I need to build my page to
actually display the image.

*Tall Computing*
*rogersgj@tallcomputing.com <rogersgj@tallcomputing.com>*

**Comment by osvalth** [comment]
Excuse me! How to use <body onload="UTIF.replaceIMG()"> in Nuxt.js?
