### ISSUE TITLE
Null check missing in LZW decompress

### ISSUE THREAD

**Issue by syvaidya** [photopea/UTIF.js#10]
For some LZW compressed images, it fails at:

`var nit = tab[OldCode].slice(0);  nit.push(tab[Code][0]);`
`var OutString = tab[OldCode].slice(0);  OutString.push(OutString[0]);`

because `tab[OldCode]` is null.

Changing those lines to following fixes the issue:

`var nit = tab[OldCode] ? tab[OldCode].slice(0) : [];  nit.push(tab[Code][0]);`
`var OutString = tab[OldCode] ? tab[OldCode].slice(0) : [];  OutString.push(OutString[0]);`

Can you please merge this fix?

**Comment by photopea** [comment]
Thank you. Can you please send me some image, where the current code does not work, to support@photopea.com or here in the discussion?

**Comment by syvaidya** [comment]
I've sent mail to your email address with the sample.

**Comment by photopea** [comment]
Ok, I changed it blindly without doing any research around it. Hope it is correct :)
