### ISSUE TITLE
UTIF multiple page tiff not able to extract all images

### ISSUE THREAD

**Issue by thesunilbagde** [photopea/UTIF.js#100]
#### when i decode image its shows all ifds but when i took 2nd or any other object and pass to encode its only converted
to first file  

#### in other words multi tiff not able extract all images only first image is getting converted.

```js

const fs = require("fs"); 
const utiff = require("UTIF");
const sharp = require("sharp");

// demo file  https://github.com/johnthad/utif-demo/blob/master/images/US3139957-BW.tiff

const filedata = fs.readFileSync("./US3139957-BW.tiff");
let result = utiff.decode(filedata); 

// result show proper count
for (let i = 0; i < result.length; i++) {
     sharp(result[i]['t34675']).toFile(
        `my-changed-image-${i}.tiff`
    );

}

```

```$
npm i sharp  utif

  
```

```json
    "sharp": "^0.28.2", 
    "utif": "^3.1.0"
```

**Comment by photopea** [comment]
I never used Sharp, but I think you are extracting only the ICC profile out of images, right? https://www.awaresystems.be/imaging/tiff/tifftags/iccprofile.html
