### ISSUE TITLE
Can not decode Jpeg encoded TIFF

### ISSUE THREAD

**Issue by AidenOhk** [photopea/UTIF.js#103]
[tiff.zip](https://github.com/photopea/UTIF.js/files/7174985/tiff.zip)
Before using UTIF.js I try to test with photopea and I found it can't decode attached jpeg encoded TIff.
I made it via Preview in mac

![image](https://user-images.githubusercontent.com/90818540/133551445-60a2197d-55cd-41f0-9b3a-d3b7b6c73705.png)
It shoud be displayed like below image
![image](https://user-images.githubusercontent.com/90818540/133551544-e599616b-7a45-4302-b3fc-26349ebff967.png)
but it is displayed like this
![image](https://user-images.githubusercontent.com/90818540/133551578-9c6d875a-5dcc-44bb-b16d-1a56f0e1d77c.png)

**Comment by photopea** [comment]
I think there is a bug in your TIFF file. It says it has four channels, but in fact, it has only three channels.

But it seems like most of TIFF viewers can still handle it. So I made UTIF.js overcome this bug. A new UTIF.js is here and at Photopea.com

BTW. you should switch to using PNG, it is a much better format.
