### ISSUE TITLE
Not working image

### ISSUE THREAD

**Issue by drop1down** [photopea/UTIF.js#109]
Here is a TIF image (JPG), that is not loaded correctly - with pink background:
http://www.nightprogrammer.org/wp-uploads/2013/02/multipage_tiff_example.tif
Any other editor (Irfan, XNView, Gimp) display it correct

**Comment by photopea** [comment]
We have been discussing this file here: https://github.com/photopea/UTIF.js/issues/42 and honestly, I don't know how to fix it :/ It is a very werid case of a tiff file. Let's discuss it there.
