### ISSUE TITLE
Save as TIFF

### ISSUE THREAD

**Issue by Scimonster** [photopea/UTIF.js#11]
Any chance this library will ever add this capability? Some academic journals still require TIFFs, so they do get used.

**Comment by photopea** [comment]
We can add a function to create simple TIFFs with no compression, it would be like 10 lines of code. But still, I think it is better not to use TIFF format. Could you ask those academic journals, why don't they move to JPGs and PNGs?

**Comment by Scimonster** [comment]
I'm just the programmer here. :smile: One of the requirements is saving as TIFF.

By the way, please make sure to update the version in package.json and publish the new version on NPM so that it's usable through NPM.

**Comment by soadzoor** [comment]
If it's really just 10 lines of code, please add those 10 lines, I'm also interested in this.. :)

**Comment by photopea** [comment]
I have added the naive TIFF encoder (without any compression), so you can save images as TIFF files. It was about 75 new lines of code. The library can also work with EXIF data now (read and write).

**Comment by soadzoor** [comment]
You sir, are awesome!
