### ISSUE TITLE
Tiff file displays ok in photopea, but not using UTIF.replaceIMG()

### ISSUE THREAD

**Issue by CoenraadS** [photopea/UTIF.js#112]
Hi

I have a .Tiff file that displays correctly in Photopea, but when using this library directly via `UTIF.replaceIMG()` it displays incorrectly. Also manually calling `toRGBA8` gives wrong result.

I do not want to share the image publicly, but can make it available privately.

I tried from latest commit: https://github.com/photopea/UTIF.js/blob/09af57503292b66ae657e1a5f4742fa248a91e9d/UTIF.js

**Comment by photopea** [comment]
Could you share your Tiff file with us?

**Comment by photopea** [comment]
Could you send us your file to support@photopea.com ?

**Comment by Augus** [comment]
I have encountered the same issue and have sent the problematic file to you. Could you please check the issue again? Thank you.

**Comment by photopea** [comment]
it should be fixed now, both in UTIF.js and in Photopea.com
