### ISSUE TITLE
decodeImage"s"?

### ISSUE THREAD

**Issue by takada-masaya** [photopea/UTIF.js#113]
Hi. I don't usually use English, so I'm sorry if my writing is strange.
And since this is my first Issue submission, I'll be sorry if there's anything to bother you.

A function `decodeImage` is exported from utif.js,
but the example below uses a function called `decodeImages`.
And if replace `decodeImages` to `decodeImage`,
the code outputs an error `_utif.default.decodeImage is not a function`.
https://codesandbox.io/s/hrtt9

Could you please explain why this is happening?

**Comment by photopea** [comment]
Hi, I looked at our code: https://github.com/photopea/UTIF.js/blob/master/UTIF.js , there is no "decodeImages". 

I think your example does not use our library, but something else instad.

**Comment by takada-masaya** [comment]
I don't know the details of the example, because it isn't created by me, but I think it probably uses your library.

Just asking out of curiosity, rest assured my code is working fine.

Thank you very much for your reply and excellent library.
Have a good day&#128516;

**Comment by photopea** [comment]
okay no probelm :) maybe someone modified our library.
