### ISSUE TITLE
.cr3 format

### ISSUE THREAD

**Issue by dedelecoder** [photopea/UTIF.js#115]
Hello,

First, I would like to say thank you for the nice job you are doing.
I would like to know if it is possible to add .cr3 format decoder ?

Thanks again

**Comment by photopea** [comment]
Hi, thanks a lot!

Canon did not describe the CR3 compression anywhere. There exist some implementations, but it is a real pain to analyze them and re-implement them from another implementation. Maybe you know someone who could do it?

**Comment by photopea** [comment]
Photopea can open Canon CR3 files now! 

Could you please try to open your CR3 files in it? If it does not work, could you send me one of your files, please? :)

**Comment by dedelecoder** [comment]
Hello, i have just found your message. great job!!! it works in photopea, i have teste with an image from https://github.com/lclevy/canon_cr3#samples
Are you going to opensource the cr3 into the utif.js?

**Comment by photopea** [comment]
I am afraid we can not open-source it.
