### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'inflateRaw')

### ISSUE THREAD

**Issue by lutifyme** [photopea/UTIF.js#117]
Hello,

We have a three.js based app using utif.js to read tiff files. We're using the official tiff loader from three.js.

Most tiff files work just fine but some files throw the following error:
"TypeError: Cannot read properties of undefined (reading 'inflateRaw')"

You can see more details here: https://www.dropbox.com/s/bnmk4w17qesv36d/image.png?dl=0

Please let me know if you need me to send the file privately.

Thanks!

Goran

**Comment by photopea** [comment]
Hi Goran, currently, UTIF.js also requires a library "pako.js" to decompress files using the DEFLATE / ZLIB compression.

We can also attach our own DEFLATE decompresssor to UTIF.js, but it would make it about 4 kB larger.

**Comment by lutifyme** [comment]
Can you? That would be very nice :-) I think 4kB is small enough.

**Comment by photopea** [comment]
I have uploaded the new version, which removes the pako.js dependency. I noticed it is also faster than pako a bit :)

**Comment by lutifyme** [comment]
Thanks a lot!
