### ISSUE TITLE
Find number of channels in a TIFF image

### ISSUE THREAD

**Issue by varun-raghavendra** [photopea/UTIF.js#119]
We need an API that gives us the number of channels that are there in a TIFF file. 

I see that the NPM package TIFF (https://www.npmjs.com/package/tiff) already has this. I just do `ifd.components` and I get the number of channels in the TIFF.

**Comment by photopea** [comment]
You can directly access a TIFF tag, which contains this information.

e.g.  ifd.t277 , see https://www.awaresystems.be/imaging/tiff/tifftags/samplesperpixel.html

**Comment by photopea** [comment]
That is how they do it, too: 

https://github.com/image-js/tiff/blob/1e543c88df906f551876ed8d71f3763fc6726285/src/tags/standard.ts#L19

    0x115 == 277
