### ISSUE TITLE
UTIF depends on pako.js?

### ISSUE THREAD

**Issue by soadzoor** [photopea/UTIF.js#12]
So, I started using this lib. First of all, it's awesome, and thanks for your work, you saved me a lot of time :)

BUT I might have discovered a potential bug on line 75, it says:
`else if(cmpr==8) {  var src = new Uint8Array(data.buffer,off,len);  var bin = pako["inflate"](src);`

I don't know what it means if cmpr == 8, maybe it's not a popuplar format/compression, but if someone tries your lib with that specific TIFF file, they could have a problem. I checked, pako is undefined here, so it might tries using pako.js [https://github.com/nodeca/pako/](url) ?

I don't see pako.js in your repo anywhere, so it might causes errors on your projects, too, if they use this lib.

Anyway, I think it wouldn't be so hard to include the needed pako.js functions, so I highly recommend doing that :)

Keep up the great work

**Comment by photopea** [comment]
Hi, I have added the information, that UTIF.js depends on pako.js, to the front page.

I was a little lazy to study and implement my own Inflate algorithm (maybe it is just 15 lines of code, I don't know). It would be nice to remove this dependency in the future.

**Comment by soadzoor** [comment]
Seems like it's much more than 15 lines of code. I'm working on a typescript version and implemented it based on pako.js. It's around 2-3 thousand lines, and it seems the algorithm needs them all. There are a couple hundred lines of comments though, but it's not that easy as it first seems. Took me 5-6 hours, or more.

**Comment by photopea** [comment]
pako.js contains also the compressor (deflating), which is not required for UTIF.js  . I am pretty sure I could write the inflate algorithm in 15 lines. But it may take several hours to understand the algorithm.

UTIF.js already contains LZW decompression, which is similar to deflate, and it is quite short.

**Comment by soadzoor** [comment]
I do hope you're right, because this much code seems to be such a waste for only one kind of tiff. BTW I did only the inflate part based on this, and it's quite long, so I have doubts..: https://github.com/nodeca/pako/blob/master/dist/pako_inflate.js

On the other hand, I didn't even try to understand the algorithm, so I hope I'm wrong and it can be done with much less code
