### ISSUE TITLE
esm version

### ISSUE THREAD

**Issue by jimmywarting** [photopea/UTIF.js#122]

**Comment by photopea** [comment]
Hi, how can I help you?

**Comment by jimmywarting** [comment]
I would like to see a ESM version that's easier to just simply import.

**Comment by photopea** [comment]
What is an ESM version? Is it a feature the new Adobe Photoshop or some other program?

**Comment by jimmywarting** [comment]
nah, instead of commonjs you would use ecmascript modules and change the way you export/import the module.

basically remove all of this:
```js
;(function(){
  var UTIF = {};
  
  // Make available for import by `require()`
  if (typeof module == "object") {module.exports = UTIF;}
  else {self.UTIF = UTIF;}
  
  function log() { if (typeof process=="undefined" || process.env.NODE_ENV=="development") console.log.apply(console, arguments);  }
  
  (function(UTIF){
 
})(UTIF);
})();
```
and simply do:

```js
// at top
const UTIF = {}

// at bottom
export default UTIF
```
then you would import this like so: `import UTIF from 'utif'`

**Comment by photopea** [comment]
I am afraid I can not use modules, because each module needs a separate JS file, but I usually have hundreds of JS files, and I want to merge them by concatenating all JS files together.

Or can you create a module in a same JS file, in which you use it?

**Comment by jimmywarting** [comment]
erm, forget that i asked.
