### ISSUE TITLE
TIFF getting scrambled when rendering

### ISSUE THREAD

**Issue by max-dandres** [photopea/UTIF.js#124]
Hello,
First, thank you for the awesome work you are doing on this package!

I am running into a weird issue where I am getting a scrambled TIFF document when trying to render it using a canvas.

Before creating this issue, I went through issue #99 and used almost the exact same code shared by **Johnthad** located here: https://github.com/johnthad/utif-demo/blob/master/thumbnails-lzw.html. 

When I execute the above code snippet locally in an index.html using my file and custom api as a datasource, it is working flawlessly.
But when I use the exact same code in my Angular application (with the same file and the same datasource), I am getting a scrambled result (see screenshot and code below).

**Tiff document:**
[zipped_tiff.zip](https://github.com/photopea/UTIF.js/files/13981300/zipped_tiff.zip)

**Original document generated using the code snippet shared by Johnthad:**
![image](https://github.com/photopea/UTIF.js/assets/99491593/c5dc9a2e-b86b-4a8d-b335-8bfffe1b581e)

**"Scrambled" document generated using an Angular 17 app and using the exact code snippet shared by Johnthad:**
![image](https://github.com/photopea/UTIF.js/assets/99491593/2815a63b-8876-4310-975a-77d200cf0dfb)

**Code used to produce the scrambled image:**

(copied from here: https://github.com/johnthad/utif-demo/blob/master/thumbnails-lzw.html)

`

     private async renderTiffToCanvas(): Promise<HTMLCanvasElement> {
        // fetching TIFF document from custom C# API
        const arraybuffer = await loadUrlToArrayBuffer(this.doc.url);
        
        let pages = UTIF.decode(arraybuffer);
        UTIF.decodeImage(arraybuffer, pages[0]);
        const rgba = UTIF.toRGBA8(pages[0]);
        const canvas = document.createElement('canvas');
        canvas.width = pages[0].width;
        canvas.height = pages[0].height;
        const ctx = canvas.getContext('2d');

        if (ctx === null) {
            throw new Error("Could not load canvas 2d context");
        }

        const imageData = ctx.createImageData(canvas.width, canvas.height);

        for (let i = 0; i < rgba.length; i++) {
          imageData.data[i] = rgba[i];
        }
        ctx.putImageData(imageData, 0, 0);
        
        // When accessing this url, the generated image is scrambled
        const dataUrl = canvas.toDataURL('image/png');

        // Convert canvas to img; scale img; and add img to DOM.
        const imgObj = document.createElement('img');
        imgObj.src = dataUrl;
        imgObj.setAttribute('width', String(canvas.width * 0.5));
        imgObj.setAttribute('height', String(canvas.height * 0.5));
        
        // Here, the generated image is scrambled
        document.body.append(imgObj);
    
        // further use of this canvas also produces the same scrambled image
        return canvas;
    }
`

At this point I don't really know why my document is appearing this way. Since it is generated in the background, I don't believe the issue is due to some size constraint on the HTML itself. The only variation I see between my code and Johnthad's snippet is the package used. In my case, I am using the **utif npm package (version 3.1.0, which I assume is the latest)**, and to execute Johnthad's snippet, I am using the latest UTIF.js file that is available through this repo. 

Is there a difference between those two libraries (**npm utif v3.1.0** and **UTIF.js**)? Or am I doing something wrong in the code? 

Any help/insight on this would be greatly appreciated, thank you for reading.

**Comment by photopea** [comment]
Make sure you use the UTIF.js library from this repository. Do not use anything from npm!

**Comment by max-dandres** [comment]
Thank you for your quick response, I did attempt to include UTIF.js directly in my angular app, but that does not seem to be a straightforward process. Are there any guidelines to make this file work with Angular?

**Comment by max-dandres** [comment]
Bumping this up, I noticed that the UTIF.js file has no export whatsoever inside it, so it is not possible to consume it as-is within an Angular app (import * from 'UTIF.js'). I'd like to not have to make modifications within the UTIF.js file so that I can easily update the package whenever there are new updates. Could I get any kind of advice as to how I can use this file as a module?

Side note: I think it would be nice to mention on the repo that the npm package is pretty much useless, right now it seems like it is a legit package that is sourced by you guys (has a direct reference to this git repo with the documentation). Also, some instructions on how to integrate UTIF.js with any type of framework using modules would be very useful I think for people like me.

**Comment by johnthad** [comment]
@max-dandres I do not use Angular, but I do use UTIF.js in client-side/browser JavaScript. Try `import './UTIF.js';` then make your calls with the `UTIF` object:

```
const pages = UTIF.decode(imagebuf);
UTIF.decodeImage(imagebuf, pages[0]);
const rgba = UTIF.toRGBA8(pages[0]); 
if (rgba) {
  const canvas = document.createElement('canvas');
  canvas.width = pages[0].width;
  canvas.height = pages[0].height;
  ...
```

As for the npm package, that _is_ a pain. IIRC whoever first put that package up--not an employee of Photopea--has abandoned it and no one else can remove or modify it. Since I use UTIF.js in severals projects, I've put a copy in my company's internal repository (run with Sonatype's Nexus Repository OSS) and `npm install` from there.

**Comment by johnthad** [comment]
IIRC the copy of UTIF.js that's on npmjs.com was put there before LZW was working correctly. I see a scrambled image as you do. However your image looks fine with a newer version of UTIF.js that I copy locally and access with `<script src="./UTIF.js"></script>` in my code (https://github.com/johnthad/utif-demo/blob/master/thumbnails-lzw.html)

**Comment by max-dandres** [comment]
I feel your pain for the npm package...

Thank you very much for your help, I was able to make use of UTIF.js within my project 👌

Using `import './UTIF.js'` in my .ts file did not work, I had to include UTIF.js in a <script> tag inside Angular's index.html, then add this line in my ts file: `declare const UTIF: any`. Might consider going for a private npm package like you did.

**Comment by photopea** [comment]
> Bumping this up, I noticed that the UTIF.js file has no export whatsoever inside it, so it is not possible to consume it as-is within an Angular app (import * from 'UTIF.js'). I'd like to not have to make modifications within the UTIF.js file so that I can easily update the package whenever there are new updates. Could I get any kind of advice as to how I can use this file as a module?
> 
> Side note: I think it would be nice to mention on the repo that the npm package is pretty much useless, right now it seems like it is a legit package that is sourced by you guys (has a direct reference to this git repo with the documentation). Also, some instructions on how to integrate UTIF.js with any type of framework using modules would be very useful I think for people like me.

I never used the npm in mylife. I wrote UTIF.js and published it here on Github. The manual for the UTIF.js does not mention any NPM. If you know how to use NPM, try to get in touch with people who published it there, and ask them to take it down, or to update it somehow.
