### ISSUE TITLE
Can auto adjust the contrast according to the maximum and minimum values of the picture for display?

### ISSUE THREAD

**Issue by Achuan-2** [photopea/UTIF.js#128]
Can adjust the contrast according to the maximum and minimum values of the picture for display?

My tif pictures are mainly pictures taken by fluorescence microscope. These pictures are 16bit data, but the maximum value of the pictures mainly depends on the brightness of the fluorescence. The maximum value may not reach 2^16, and often the maximum value is only 5000.

**Comment by photopea** [comment]
UTIF is for encoding and decoding images, we do not provide any image editing tools.
