### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by Scimonster** [photopea/UTIF.js#13]
Hi, can you please keep the version on NPM updated? It just requires bumping the version in package.json, in accordance with semver, and doing `npm publish`.

Also, you can specify dependencies (such as pako) in package.json.

**Comment by Scimonster** [comment]
My workflow is exclusively via package manager for a large project, so this is actually critical for me.

**Comment by photopea** [comment]
I don't use "npm" in my workflow, and I am too lazy to learn how to use a new software. Can you put it onto "npm" yourself?

**Comment by Scimonster** [comment]
Yes, but only if you give me access to this repository to be able to update package.json as needed, or if you commit to keeping it updated in accordance with [semver](http://semver.org/).

**Comment by Scimonster** [comment]
The alternative is for me or someone else to make a pull request every time a change is made to update the version, but that may be more hassle.

**Comment by photopea** [comment]
I tried to ask for some new features: https://github.com/npm/www/issues/173

**Comment by Scimonster** [comment]
It doesn't look like that's going too well, and it would probably be several months before something like that is ready in any case. I would really like to be able to use your package in a few days.

I can think of the following options, let me know what you prefer:
 - Add me as a maintainer to this git repo (and others that should be published) to manage the Node side of things. I'll keep the version on NPM up to date, and can add you as a maintainer when you're ready.
 - Don't add me here, someone has to keep the repo Node-friendly. I'll keep NPM up to date.
 - I fork the repo and deal with the horror of merging git branches across forks, and maintain NPM.

**Comment by photopea** [comment]
I have added you as a colaborator. Don't know how to make you a maintainer.

Please do whatever you want, but keep the UTIF.js file usable in a browser as it is, without any additional processing by 30 more programs.

**Comment by Scimonster** [comment]
Collaborator, maintainer, same thing. :)

I will make sure to keep it usable in a browser.

Thanks.

**Comment by syvaidya** [comment]
@Scimonster would you please also add dependency for jpg.js (https://github.com/notmasteryet/jpgjs) in package.json? This is required for TIFF files having image data using JPEG compression. Maybe it can be marked as optional dependency (if it is allowed).

**Comment by photopea** [comment]
@syvaidya  These dependencies are quite confusing ... I think that 90% of UTIF.js users will never deal with TIFF images with JPEG or Deflate compression, i.e. they don't need jpg.js or pako.js .  But the mechanism of NPM will include these dependency libraries anyway (making websites load slower, data transfer higher ...).

What would be a better way to deal with it?

**Comment by Scimonster** [comment]
NPM is mainly designed for NodeJS, which is server-side and as such has no on-demand network transfer.

For people using NPM to manage packages for client-side use, either simply accept the extra dependencies, or you configure your build tools (browserify, webpack, etc) to simply mock it out.

**Comment by syvaidya** [comment]
Maybe you can just mention in README or documentation that jpg.js should be manually added to the page if user wants to decode JPEG compressed files.

**Comment by photopea** [comment]
Ok, so @Scimonster  please metion these libraries in NPM manifest.

**Comment by Scimonster** [comment]
Huh. I published to npm but forgot to push to GitHub. Whoops! Pushed now.

**Comment by primozcerar** [comment]
Can you please update npm with the latest changes ie push a new version?

**Comment by photopea** [comment]
@Scimonster Can you?

**Comment by Scimonster** [comment]
Done
