### ISSUE TITLE
Unable to decode Utif layes

### ISSUE THREAD

**Issue by AnkitSE01** [photopea/UTIF.js#131]
[flower-1.zip](https://github.com/user-attachments/files/17179375/flower-1.zip)

i am unable to see layers of this file or nay tif format file in photopea its working preety fine can you please guide to unlock all layers as its happening in photopea

evertime i am getting idf with array 0

**Comment by photopea** [comment]
Do you find any software or a library, which can decode layers inside your file, other than Adobe Photoshop and Photopea?

Your TIF file contains a single image (single layer) and metadata. The metadata contains a PSD file. Photopea and Adobe Photoshop detect and decode that PSD file and ignore the main content of a TIF file.

UTIF.js decodes your TIF file just as any other TIF library would. The PSD decoder of Photopea is not a part of UTIF.js and is not open source.
