### ISSUE TITLE
Converted image inverts colors

### ISSUE THREAD

**Issue by kgrimes2** [photopea/UTIF.js#16]
I have been trying to use this software with the attached .tiff image. The image is successfully converted, but it appears that the colors are inverted. I've attached the pre-encoded image and the encoded image.

[W1829067576_15.IMG.tiff.zip](https://github.com/photopea/UTIF.js/files/1265185/W1829067576_15.IMG.tiff.zip)

![download 1](https://user-images.githubusercontent.com/13686706/29896449-de6f1e9a-8d91-11e7-8b33-604006e61574.png)

**Comment by photopea** [comment]
Hi, it was fixed. Sorry for the delay.
