### ISSUE TITLE
Support for grayscale Jpeg images

### ISSUE THREAD

**Issue by alu305** [photopea/UTIF.js#17]
In order to support JPEG greyscale images please update the following line(within _decodeNewJPEG function) from:

img["t262"][0] = 2;

to:

if(img["t262"][0] == 6){
	img["t262"][0] = 2;
}

**Comment by photopea** [comment]
Hi, can you show us a TIFF image, for which it is useful?

**Comment by alu305** [comment]
The grayscale images have only one sample per pixel vs 3 sample per pixel for color images.
See attache tiff file.
[346-0004_01.zip](https://github.com/photopea/UTIF.js/files/1315448/346-0004_01.zip)

**Comment by photopea** [comment]
Hi, ok, I changed that line. Thank you very much! :)
