### ISSUE TITLE
Image does not display correctly after decoding to RGB8

### ISSUE THREAD

**Issue by cloutiertyler** [photopea/UTIF.js#18]
Before processing:
[original.tif.zip](https://github.com/photopea/UTIF.js/files/1459433/original.tif.zip)

After toRGB8:
![image](https://user-images.githubusercontent.com/6432361/32633232-91895a30-c55b-11e7-9090-f516316986d9.png)

It looks like it some scaling might be off? The white channel looks like it's getting clipped in all except the darkest locations.

**Comment by photopea** [comment]
Hi, I updated the library. Your file works well in Photopea.com , which uses UTIF.js

**Comment by cloutiertyler** [comment]
Excellent! I'll check it out. Thanks so much!
