### ISSUE TITLE
Tiff Image not displaying correctly.  

### ISSUE THREAD

**Issue by rogersgj** [photopea/UTIF.js#2]
I am sorry to say I found another image that won't display correctly.  It doesn't lock the page, but it only display maybe a 1/100 of the image.  

I will zip it and attach it.  Otherwise it works great!  Getting much further than I did with tiff.js in IE.  Not getting any memory issues.  Running in a loop it doesn't seem to process the entire 81 page tiff.  ALways stops in the 70's mark.  I am working on that one.  The 
[D8HW001.tif.zip](https://github.com/photopea/UTIF.js/files/922704/D8HW001.tif.zip)
file is attached in a zip.

**Comment by rogersgj** [comment]
Just want to throw out there, If I crop the image so there is no top border, the image appears perfectly.  The documents I work with have a lot of these type borders on them.

**Comment by photopea** [comment]
Ok, I fixed it, please use the new version. It took me quite a long time to figure out, that I just need to add 10 characters to my code :D

https://github.com/photopea/UTIF.js/commit/3c11212d55b84b37cbb1d83aaca77ab09691df1f#diff-d890c282f9ccbc9fb5971048236dd336

Thank you very much for helping me improve this library. I will be very glad, if you find even more bugs :)
