### ISSUE TITLE
UTIF cannot be used inside service workers because of dependence on window

### ISSUE THREAD

**Issue by manticorp** [photopea/UTIF.js#20]
At the top of UTIF.js, we have:

```
// Make available for import by `require()`
if (typeof module == "object") {module.exports = UTIF;}
else {window.UTIF = UTIF;}

var pako, JpegDecoder;
if (typeof require == "function") {pako = require("pako"); JpegDecoder = require("jpgjs").JpegDecoder;}
else {pako = window.pako; JpegDecoder = window.JpegDecoder;}
```

To make it work in service workers requires adding just 1 line:

```
if (typeof window === 'undefined' && typeof self !== 'undefined') window = self;
```

Any thoughts before I submit a pull request?

**Comment by photopea** [comment]
Hi, I have no experience with Service Workers, so I will have to believe you. 

I relpaced every "window" occurence by "sefl".

**Comment by manticorp** [comment]
That should work fine in most browsers and contexts from what I can tell 👍
