### ISSUE TITLE
The decoding methods don't work right on one of my test images, due to rounding issues when working with bits

### ISSUE THREAD

**Issue by makr28** [photopea/UTIF.js#30]
Note: I have a fix for this issue and will get it in this week but wanted to log it. 

What the image looks like with UTIF
![image](https://user-images.githubusercontent.com/37880962/39126012-f6154e06-46ce-11e8-9845-c7f3e5d4286b.png)

How the image should look 

![image](https://user-images.githubusercontent.com/37880962/39126068-25861166-46cf-11e8-965c-18b935c69d78.png)

**Comment by photopea** [comment]
Hi, I think I can fix it myself. Could you send us your TIFF file to support@photopea.com ?

**Comment by makr28** [comment]
thanks, for handling this so quickly but testing with the updated code, it still doesn't look write. Below is what is currently happening. I made sure it's hitting the new UTIF code when I ran the test. 

![image](https://user-images.githubusercontent.com/37880962/39134783-6ea9801a-46e5-11e8-8ebe-e7ca1b72f10e.png)

**Comment by photopea** [comment]
Hi, I don't understand how did you got an image that you are showing. It is 597x762, while your original TIFF is 5103x6589 .

I converted your TIFF into PNG (using Photopea with the latest UTIF.js) and below is what I got. It corresponds to how I see your TIFF in Windows Photo Viewer. 
![dpi600kofax](https://user-images.githubusercontent.com/15955558/39135708-db023cc8-4719-11e8-98d2-ff22d71a3939.png)

**Comment by makr28** [comment]
The lines in the screenshot I just attached are not solid, It does not look like what you attached.

See what I've circled, those lines should be solid 

![image](https://user-images.githubusercontent.com/37880962/39136456-4af3ffca-46e9-11e8-814e-2f61131196bc.png)

**Comment by photopea** [comment]
You need to run Photopea on a screen with larger resolution, so you could see the original 5103x6589 image with solid lines.

This is the way how preview in Photopea works. It has nothing to do with UTIF.js .

**Comment by makr28** [comment]
You're right, I tested on something else and you're fix does work, it was something on our side. Thanks for your help! :)
