### ISSUE TITLE
Support for BigTIFF format for data larger than 4GB?

### ISSUE THREAD

**Issue by oeway** [photopea/UTIF.js#31]
I am thinking about the feasibility of using bigTIFF image format for very large image sequence, and I would like to have your opinion on the following aspects:

1. add big tiff support according to [the bigTIFF standard](https://www.awaresystems.be/imaging/tiff/bigtiff.html). Would this be possible? Even better thing is to have the "[OME-XML metadata](https://docs.openmicroscopy.org/ome-model/5.6.1/ome-tiff/file-structure.html)" supported, but that should not be a problem.

2. we need to streaming data from the disk rather than try to load the entire file into memory. After a quick investigation on this library, I think I need to first read the ifds with UTIF.decode, then, when the user request a certain frame, the decode the requested frame on demand by reading the requested block of file from the disk, and decode it with UTIF.decodeImages. The question is, would it be possible to determine the number of frame first without loading the whole file or searching through the whole file? Is it feasible for the current library to do that?

A related question is that, currently, I tried to use Photopea to load a big file(<4GB) with thousands of tiff frames, I think it tries to load everything to the memory, so the interface got stucked and crash. That maybe not a problem for Photopea and it may out of the scope of Photopea itself, but my question, would it possible for Photopea to mantain a "virtual file" which stays in the disk and only access it on demand?

BTW, Thanks for nice work, I like PhotoPea a lot.

**Comment by photopea** [comment]
Hi, we plan to support huge files with Photopea, too: https://github.com/photopea/photopea/issues/447

UTIF.js is meant for the web, and currently, there is no interface for a webpage to load and store data from a hard drive.  BTW. why don't you split your large Tiff into multiple Tiffs? I think it is more comfortable to work with one independent file, rather than a byte portion of some huge file ("streaming"). Google Maps with satellite photos also don't store the whole world inside one 100TB tiff.

**Comment by oeway** [comment]
Hi, thanks for the quick response, and good to hear that you are working on huge files.

Here, I prefer multi-frame tiff within a huge file is because when the number of frame goes up to 10,000 or even more, there is a huge overhead for the file explorer to even list all the files, we suffers a lot because of that and it introduce the overhead when copying and transmission. 

Yet another reason is that, imagine a case when you want to view/process 10,000 frames of tiff images in the browser, and the process you try to do will combine information from all the frames of these tiff images. When the user try to select these files, it will be painful to select all these files in a file dialog. Yes, chrome support folder selection, but not other browsers. For simplicity, I would prefer to select just a single huge file, and keep it in the disk and request on demand. Also notice that, here, I am talking about reading these files. For writing, it's not my concern for now, but I am looking into: [StreamSaver](https://github.com/jimmywarting/StreamSaver.js).

**Comment by photopea** [comment]
"file explorer" - what do you mean? If your files are named e.g. image0, image1, image2 .... the app would load them automatically by name. There is no need to run a file explorer.

BTW. have you thought about using some compression? It could be good for each frame separately, but maybe also compress in between frames. E.g. in video, the first frame is stored as full, and other frames are stored as differences from the first frame (very small information). This inter-frame compression also exists in GIF and APNG.

**Comment by oeway** [comment]
"file explorer" means the "Finder" app on MacOS for example, we used a remote samba server to store these small single-frame tiff files (~2MB each), the Finder hangs when we even just click on the folder when it try to list all the files. That's why we are moving to the single multi-frame tiff file solution, and ideally bigTIFF solution as mentioned above. 

The other reason as mentioned above, browsers except chrome can allow user to select a folder. Imagine are asking the user to select the files with a file dialog or drag 10,000 files into the browser, what will happen is in our case is the file dialog just hangs for quite a while to list all the files. In case of drag'n'drop, you still need the file explorer to list the entire folder, and then drag all the files into the browser.

That's right, I do want to do that, that's why requested the apng 16-bit encoding feature, the plan is to allow user read these tiff files produced by other software(e.g. ImageJ/Micro-manager), in a single bigTIFF format, and then process them in the browser, when export the results, we use your UPNG.js library to encode into .apng file.

But right now, not much I can do with the generation of those tiff files.

Hope I am clear enough.

**Comment by photopea** [comment]
I have no experience with working with so large files in Javascript (which do not fit inside RAM). 

What about having all TIFFs separate, but put them all into a one ZIP? The user will open a single ZIP file, your program would take a TIFF image from ZIP and process the small file with UTIF.js . So you just need a "streamed" ZIP library.

**Comment by oeway** [comment]
I am thinking about that, we could just read part of the file with by [slicing files](https://www.html5rocks.com/en/tutorials/file/dndfiles/#toc-slicing-files), then decode that part of the file without read the actual content. Since in the ifds you can find the offset, we can also just use the slice api for reading any frame from disk and then decoding the image.
What do you think about that?

For the zip idea, I am already using jszip library, but so far as I know, when you use some compression, you will need to decompress the whole file.

https://stuk.github.io/jszip/documentation/limitations.html
> If you read a zip file compressed with DEFLATE and call generate with the STORE compression, JSZip will have to decompress everything.

**Comment by photopea** [comment]
Files from ZIP can be read separately, without decompressing the whole archive. Maybe you could ask JSzip authors to provide such feature. BTW. I am using my own UZIP.js for zip, but it is not public.

**Comment by photopea** [comment]
I am closing it.

**Comment by photopea** [comment]
Yes, it is possible to do with ZIPped files. But UZIP.js can not do that currently (we never had so huge ZIPs).
