### ISSUE TITLE
JpegDecoder is undefined when jpgjs is loaded - module.exports is empty

### ISSUE THREAD

**Issue by makr28** [photopea/UTIF.js#32]
I have a node project and I did an "npm install utif". This correctly brought in pako and jpgjs as well.
Pako can be found and is fine. But jpgjs module.exports is not being set.

In jpgjs line 102
if (typeof exports === "function") {
    module.exports = {
        JpegImage: JpegImage,
        JpegDecoder: JpegDecoder,
        JpxDecoder: JpxDecoder,
        Jbig2Decoder: Jbig2Decoder
    };
}

Looking in the debugger typeof exports evaluates to 'object'

This may be an issue with Jpg.js but I wanted to ask if you had come across this issue?

Thanks

added notes: 
-Using npm version 8.9.4
-I am going thru the require('jpgjs') code path to load jpegDecoder

**Comment by photopea** [comment]
Hi, I never used npm or Node.js . I use UTIF.js in a web browser.

Maybe @Scimonster  could help us?

**Comment by makr28** [comment]
@photopea  Hi, I figured out what was wrong with jpg.js but they have not been active for a few years. I forked jpgjs to my github (https://github.com/makr28/jpgjs) would you be willing to switch the dependency to it? If you don't like that idea would you be willing to fork it and put the change that fixes it in?

Thanks!

**Comment by photopea** [comment]
The JpegDecoder that I use along with UTIF.js is a copy-pasted fragment of pdf.js , see here: https://github.com/mozilla/pdf.js/issues/6128

TIFF files containing JPEG compression are a "legacy thing". I recommend to convert them all to a regular JPEG and then use these JPEGs. Other compressions (CCITT, LZW, PackBits) are included in UTIF.js and do not require any additional library.

**Comment by photopea** [comment]
@syvaidya You are the one who understands JPEG! :)  Could we insert all necessary parts of JpegDecoder into UTIF.js (only those JPEG features, that can be used in TIFFs)? How much code would it be? It is a bit unpractical to have a dependency.

**Comment by makr28** [comment]
In your package.json you have:

"dependencies": {
"jpgjs": "github:notmasteryet/jpgjs",

So you already are pulling in the dependency

**Comment by makr28** [comment]
If you want to take that dependency out, I can just put my version of jpg.js as a dependency in my project

**Comment by Scimonster** [comment]
I'll take a look at npm and the dependency stuff over the weekend.

**Comment by makr28** [comment]
Thanks

**Comment by makr28** [comment]
Actually testing with the dependency take out of utif.js's node modules, it doesn't work right,  so we do need you to keep the dependency in your package.json but switch it to the working version.

It's the only way utif will work for node projects. This shouldnt affect what you use utif for as you dont use the node_modules folder or package.json in your projects but node projects will. And since you already have the dependency there, it won't be adding anything to utif.

Thanks :)

**Comment by k1nger** [comment]
Yes Tiff files containing JPEG is a legacy thing, but there are many files still in existence today that are still that data type. Unfortunately managing long standing enterprise applications we need this support as well. 

JPGJG was forked from mozilla/pdf.js 3-4 years ago. mozilla/pdf.js has long since enhanced their jpgjs while this has remained stagnant and unresponsive. That and it doesn't even follow modern ecmascript standards which is causing the bug in this issue. 

+1 to either remove the dependency (while keeping functionality) or to pull in a more modern one that can be used with modern javascript development practices.

**Comment by photopea** [comment]
@k1nger  I would like to ask Mozilla to publish their JPEG decoders as a separate library (and maintain it in that library), and pdf.js would have a dependency on that library.  Otherwise, Github would be filled with dozens of copy-pasted fragments of pdf.js, which are not maintained by anybody anymore. Would you support me and help me emphasize this to pdf.js developers?

**Comment by k1nger** [comment]
Yup, I think that's a good idea.

**Comment by makr28** [comment]
@photopea Another way would be to change your package.json where you are currently pulling in the unworking jpg.js to pull in pdf.js and switch the require to use their version of jpg.js and the jpegDecoder. 

I support your campaign to have pdf js extract the jpegdecoder and I will comment on the issue but as of right now it doesn't look like they are going to anytime soon :(  

If you aren't going to switch the jpg.js dependency then can you please  remove  the line  "jpgjs": "github:notmasteryet/jpgjs", from your package.json as it is currently useless if it doesn't export the jpegdecoder correctly. And to make UTIF work for NodeJs projects can you please remove the require line and add a method to set jpegDecoder to a variable passed in. These proposed changes only affect Node projects. 

As with @k1nger  I am also working in enterprise software that requires us to support older tiff images.

Thanks

**Comment by k1nger** [comment]
@Scimonster Have you made any progress with what you were looking into? 

@photopea Since it looks like Mozilla is unresponsive I think it may be best to move forward with this issue and drop another release to npm. I can help.

**Comment by Scimonster** [comment]
I switched the dependency to @makr28's fork of jpgjs and pushed it to NPM. Sorry it's taken me so long, i haven't been around very much. If someone else wants to take over managing the NPM side of things i'm happy to let them, assuming @photopea agrees.
