### ISSUE TITLE
JPEG error: SOI not found

### ISSUE THREAD

**Issue by makr28** [photopea/UTIF.js#41]
I don't think this would be specific to Node.js but I don't know for sure. 

But I am getting the following when using the latest UTIF master code, when I try to view a tiff document that uses new style Jpegdecoder.

The following code is in method UTIF.decode._decodeNewJPEG = function(img, data, off, len, tgt, toff)

`parser =  new UTIF.JpegDecoder();`

returns

```
g {M: null, B: -1}
   B: -1
   M: null
```

then

`parser.parse("buff")`

returns

`g {message: "JPEG error: SOI not found"}`

**Comment by photopea** [comment]
Hi, could you please give us a file, which does not work with UTIF.js ? Are you sure that file worked before?

**Comment by makr28** [comment]
I tried multiple online converters to get new type 7 examples (I will email them to you. They do not work either. I can't get any Type 7 working.

**Comment by photopea** [comment]
Hi. So this error was not related to a JPEG library, but to an incorrect reading of data from IFD. This bug appeared several months ago. Too bad you did not update your UTIF.js back then, so we could fix is earlier. All this time, I thought it is related to a JPEG library.

It was fixed and it should work now. But there is another bug - some files appear to have incorrect colors: https://github.com/photopea/UTIF.js/issues/42

**Comment by makr28** [comment]
Yeah I get that, unfortunately we couldn't use your UTIF without it being thru an npm release for stability reasons. Like if you update master and were using the your git URL in our package.json, we get every update. But for npm we don't automatically get new stuff unless we specifically change what version we are requesting.  So Once @Scimonster releases we can switch it back to yours.

Thanks for working on this by the way, I had left my work computer at work and didn't get a chance to send you the requested things.
