### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by hipstersmoothie** [photopea/UTIF.js#43]
Since the dependency troubles #39 have now been solved can we get a release?

**Comment by cccRaim** [comment]
same problem, `jpgjs` cause install action slowly

**Comment by photopea** [comment]
@cccRaim what do you mean? What is "jpgjs" and how is it related to UTIF.js ?

**Comment by cccRaim** [comment]
@photopea 
The `Dependencies` on NPM
https://www.npmjs.com/package/utif

![image](https://user-images.githubusercontent.com/7681138/44651207-48fa4400-aa1b-11e8-9536-af59bf0d0d2e.png) 
---
And package.json contain the `dependencies `, it declare the dependencies in this project, 
![image](https://user-images.githubusercontent.com/7681138/44651386-d50c6b80-aa1b-11e8-8aad-51ed5554cd16.png)
But the strange thing is, when I search `jpgjs` in code, I can't find
Emmmmm, so I search the history in `UTIF.js`, find the code blow
![image](https://user-images.githubusercontent.com/7681138/44652060-88299480-aa1d-11e8-8f9a-35bc9b5d8e81.png)
You delete the `jpgjs` dependency, so the `jpgjs` in package.json is useless.
And now you delete `jpgjs` in package.json.
All work is done! But there has a last thing to do.

You need publish this project to NPM.

**Comment by photopea** [comment]
As I said, I never used NPM. @Scimonster , please update the NPM once you have time :)

**Comment by cccRaim** [comment]
@photopea thx very much

**Comment by rthomps7** [comment]
Thanks, @photopea. @Scimonster  - any chance you can update?

**Comment by hipstersmoothie** [comment]
@photopea I've been getting bug reports *every* day. Currently this dependency problem breaks on the following platforms:

* AWS
* Heroku
* Travis CI
* Windows 
* Netlify
* elasticbeanstalk
* Most other continuous integration environments

@Scimonster this is quite an important issue that's effecting dozens if not hundreds of users

**Comment by photopea** [comment]
@hipstersmoothie I can let you do it yourself instead of @Scimonster , as I am also officially the maintainer of the NPM, too. Can you tell me what should I do?

**Comment by hipstersmoothie** [comment]
https://docs.npmjs.com/cli/owner

you should be able to run the following to add me as a maintainer (note I have never done this myself)

```sh
npm owner add alisowski utif
```

**Comment by hipstersmoothie** [comment]
Or you could just do it yourself. It's almost the same amount of commands. Just make sure you're on master

Steps:
1. change version in package.json to 2.0.1
2. run `npm publish` at the command line
