### ISSUE TITLE
How to scale image to smaller canvas?

### ISSUE THREAD

**Issue by reecefenwick** [photopea/UTIF.js#45]
Thanks for the great library!

I'm trying to use this with React, and used the code for `UTIF. replaceIMG()` to get me started.

I'm using your sample image from https://www.photopea.com/api/img/G4.TIF which is quite large

I've setup a sanbox with a 600x600 canvas and I'm trying to scale that image to fit in with everything visible, but cannot seem to get context.scale(x,y) to work.

Are you able to offer any advice on how to scale the image? I see photopea handles it way, so figured I'm just doing something wrong.

**Comment by photopea** [comment]
Hi, what exactly is your goal?  replaceIMG() lets you comfortably use TIFF images in <img src="..." /> elements. To make them smaller, you could apply a CSS for all IMG tags. Or you can copy-paste the replaceIMG() function and rewrite it your way.

If youwre working just with one image, use regular parsing, convert the image to RGBA8 and scale it down by computing an average pixel for each NxN pixels (with a for loop).
