### ISSUE TITLE
16 bit tif file suport?

### ISSUE THREAD

**Issue by photopaul25** [photopea/UTIF.js#46]
If I load a 16 bit tif file from Adobe Lightroom with or without compression into Photopea I end up with a corrupted output image. 

<img width="1680" alt="screen shot 2018-10-07 at 11 38 25 pm" src="https://user-images.githubusercontent.com/43944052/46591672-42cf9c80-ca8a-11e8-9e1f-6e82bb6ae666.png">

Here is the same image as a 8 bit tif:
<img width="1680" alt="screen shot 2018-10-07 at 11 38 45 pm" src="https://user-images.githubusercontent.com/43944052/46591698-714d7780-ca8a-11e8-8184-9d721579aff7.png">

I don't see any errors in the Chrome debugger when opening the 16 bit tif. Let me know if there is anything else I can do to help debug this. Currently I am trying to find a solution to import and export 16 bit tif files for processing in javascript. If I can find a pure JS solution that would be ideal.

**Comment by photopea** [comment]
Hi Paul, could you send us your TIFF image to support@photopea.com ?

**Comment by photopaul25** [comment]
@photopea Done! I sent the 8bit and 16bit versions. Let me know if you need more files.

**Comment by photopea** [comment]
Ok, so as I expected, it was just an error in Endianity. Please, load the new UTIF.js . You can open your image in Photopea, too. Thanks for reporting it!

**Comment by photopaul25** [comment]
Thanks for the quick fix I can confirm my 16 bit uncompressed files are opening properly now! 

A 16 bit tiff from Lightroom with Zip compression is still showing the same issue. Would you like me to send you one? 

What do you think would be the best way to get the 16bit RGB values? From looking over the code it appears that the data array inside decodeImages will hold all the decompressed bytes and it's the function toRGBA8 that does the translation from bytes to a RGBA array. So  I am thinking I would want to  create a toRGB16 function that will return a Uint16Array. Does this sound like the right path?

**Comment by photopea** [comment]
Sure, send me the TIFF file to support@photopea.com .

I think it is enough to access just out.data array. You may need to reorder bytes depending on "isLE" property. Note, that toRGBA8 works with any TIFF file (even with 1bit black-and-white images).

toRGBA16() is rarely needed. It would expand 1bit images 64 times. You can make your "local" toRGBA16 function  for your purpose.

**Comment by photopea** [comment]
@photopaul25 This time, there was an error with Prediction. I fixed it again. Thanks! :)

**Comment by photopaul25** [comment]
@photopea Your welcome, glad I could help! Lightroom 16 bit images with and without zip compressions are working for me now! 

Making a local function makes sense. I didn't even think about 1 bit tif files. I am so used to a raw photography workflow where those files are 12-16 bit and some programs even generate 32 bit files for HDR.

**Comment by photopea** [comment]
BTW in the last version, I also fixed the Endianity problem (I make sure, that it is always a Little Endian).

So you can simply do 

    var data = new Uint16Array(ifds[0].data.buffer);
