### ISSUE TITLE
LosslessJpegDecoder is undefined

### ISSUE THREAD

**Issue by c-anna** [photopea/UTIF.js#49]
Hello,

I've been using Jimp (https://www.npmjs.com/package/jimp) within an AWS Lambda function to do some image processing. Recently we encountered a strange error where the Lambda fails with the following error message:

```LosslessJpegDecoder is not defined```

`LosslessJpegDecoder` was not something I'd seen before, so I did some investigating and found that it occurs in UTIF.js (line 243 in v2.0.1, the version my project is using). There's a comment that says the LosslessJpegDecoder is relevant to DNG files and isn't available in UTIF.JpegDecoder -- it makes sense that I would encounter this because my Lambda is usually working with DNG files.

Here's the line where a `LosslessJpegDecoder` gets created:

```javascript
if(img["t262"]==32803) // lossless JPEG (used in DNG files) is not available in JpegDecoder.
	{
		var bps = img["t258"][0], dcdr = new LosslessJpegDecoder();
```

The string `LosslessJpegDecoder` does not appear anywhere else in UTIF.js. Where is it supposed to come from? It is not being imported or required anywhere. 

Strangely, Jimp also uses an identical snippet of code, and also doesn't define, import, or require LosslessJpegDecoder. I'm not sure which of these packages is actually throwing the error but it's clearly related to the same cause.

Is this a bug? If not, where is `LosslessJpegDecoder` supposed to be defined?

Thank you,
c-anna

**Comment by photopea** [comment]
Hi Anna. UTIF.js is a library for decoding TIFF images. You seem to be decoding DNG images.

I do use UTIF.js at Photopea.com to decode DNG. I attach LosslessJpegDecoder.js using a <script> tag of HTML. I never used Node.js, NPM or AWS Lambda, I don't even know what it means.

I don't want all users of UTIF.js attach LosslessJpegDecoder to their files, because they will not need it for decoding regular TIFF files. I hope you will be able to attach it somehow in your own environment.

**Comment by c-anna** [comment]
Thank you for your help. When I opened this issue I thought I had been processing DNGs for some time using Jimp (which itself uses UTIF.js). After some investigation, I realized that I'd only started using it in the last day or so -- exactly when this error cropped up. If DNGs are outside the purview of UTIF.js then I will find a way to attach LosslessJpegDecoder to my project.

Thanks again for your help!

**Comment by photopea** [comment]
We had the similar problem with JPEG-compressed TIFFs. They are quite rare, but users had many problems, so we attached the complete JPEG decoder into UTIF.js .

**Comment by rdhenderson** [comment]
Would it be possible to include error handling to clarify that a peer dependency is required to process DNG? 

```
var bps = img["t258"][0];
var dcdr = LosslessJpegDecoder && new LosslessJpegDecoder();
if (dcdr === undefined) {
    throw new Error('LosslessJpegDecoder is undefined.  In order to process DNG images, include lossless-jpeg-decoder as a peer dependency.');
} 
```
or 
```
var bps = img["t258"][0], dcdr;
try {
  dcdr = LosslessJpegDecoder && new LosslessJpegDecoder();
} catch(err) {
    throw new Error('LosslessJpegDecoder is undefined.  In order to process DNG images, include lossless-jpeg-decoder as a peer dependency.');
} 
```
