### ISSUE TITLE
16 bit Big Endian Tiffs not rendering correctly

### ISSUE THREAD

**Issue by Blatman** [photopea/UTIF.js#50]
Just trying UTIF.js in desktop mode and it works well with Little-Endian TIFF's (II) but not so well if the TIFF is Big-Endian (MM) - the Big Endian ones also fail using Photopea online.

In desktop mode I am using the UTIF.replaceIMG() method which works well.

I have attached a zip file with the test files - the two 8 bit files were used as the source in LR for the 16bit LR pano and also for a 16bit pano produced with Panorama Stitcher (panoramastitcher.com). PS as far as I can tell always outputs a Big-Endian 16bit file (with alpha channel). The workround for me at the moment is to re-process the Big-Endian file into a little-Endian one like LR using ImageMagick but I thought that UTIF.js had the ability to do such conversions.

Note: NPM version of UTIF.js) needs updating for the latest LR fix (#46) - I had to use the master zip from GitHub.

Bad render on Photopea (BE-16bit)
<img width="622" alt="bad-be-16bit" src="https://user-images.githubusercontent.com/11089335/47506302-ad911e00-d867-11e8-9e4a-ed363a4f2b85.png">

OK render on Photopea (LE-16bit)
<img width="666" alt="ok-le-16bit" src="https://user-images.githubusercontent.com/11089335/47506356-c4d00b80-d867-11e8-8506-558cd51a3832.png">

Test files attached -
[Panos.zip](https://github.com/photopea/UTIF.js/files/2515247/Panos.zip)

**Comment by photopea** [comment]
Hi, I fixed it. I updated Photopea and UTIF.js file.

The problem was not in Endianity. One of your images contained three samples, while another contained four samples per pixel. The code was not ready for four-channel 16-bit images.

**Comment by Blatman** [comment]
Superb - works great even with a 374M file from PS - I guess the fourth channel may have related to the alpha channel as that was the only real difference I could see apart from the Endianess.
Cheers
