### ISSUE TITLE
Canon CR2 (type of TIFF) just shows loading on Photopea and no display with UTIF

### ISSUE THREAD

**Issue by Blatman** [photopea/UTIF.js#52]
Tried .cr2 file with UTIF and it doesn't work so tried it on Photopea and just get loading.
Tried a LR generated dng on UTIF and it didn't work but works OK on Photopea so will try UTIF again for the dng - should it work using the UTIF.replaceIMG() method?

Not sure if the cr2 problem is a major tweak but I think the Maker Notes are the main difference from a normal tiff (tiff is Little Endian (II)).
.cr2 attached -
[IMG_0290.CR2.zip](https://github.com/photopea/UTIF.js/files/2520808/IMG_0290.CR2.zip)

**Comment by photopea** [comment]
Hi, the CR2 format is based on TIFF, but many of its areas (mainly the compression) are not publicly described anywhere.  We do not provide the CR2 support in UTIF.js or Photopea at the moment.

If you know anybody, who could help us with implementing CR2, it would be amazing!

**Comment by Blatman** [comment]
Yup Ok - info on it does seem thin on the ground. I don't know anybody at this stage but this page is done by somebody who is keen to find out all about it - http://lclevy.free.fr/cr2/ - possibly not enough known to do the coding (dcraw will do it but is very slow).

Cheers,
Blane

**Comment by Blatman** [comment]
Good to see - my use case is for an offline app so given that UTIF will display a TIFF in HTML I've gone down the track of processing the raw's to an intermediate PNG which can then be converted to TIFF and displayed with UTIF - since most raw's can't be (re-)written to by exiftool, etc I've run with TIFF as the format of choice since it is pretty well a standard in the archival/scanning/photo world. Admittedly direct DNG/CR2 display would be nice ...
Cheers.

**Comment by Blatman** [comment]
Yeah that would make utif.js useful for thumbnail/preview/DAM use with DNG/CR2 directly with reasonable speed

**Comment by photopea** [comment]
Hi, I updated UTIF.js here, it will show previews of DNG/CR2/NEF files.

**Comment by Blatman** [comment]
Very good, appears to work well for previews - .3fr (Hasselblad) raws will also show preview OK if 3fr added to the sufs var line 964
Cheers
