### ISSUE TITLE
DNG not working with UTIF.js

### ISSUE THREAD

**Issue by Blatman** [photopea/UTIF.js#53]
Looking at the readme it suggests that DNG should also work and I see the LosslessJpegDecode has been included however after much pulling out of hair I can't get it to work.
Tried it with UTIF.replaceDngIMG method but that seems to only work with ifds[0] and DNG I think uses ifds[1] for the full image. With ifds[1] it works upto the UTIF.decodeImages part but then the rgba object is just full of 0's - I think at some stage I got an image when using ifds[0] but of course with dng that is a smaller sub-image - please advide if I am missing a simple trick or whether different code is required. I have attached a test image which does work on Photopea online (it is non compressed dng within the zip).

Cheers.

[test.dng.zip](https://github.com/photopea/UTIF.js/files/2577726/test.dng.zip)

**Comment by photopea** [comment]
Hi, UTIF.js only lets you parse the DNG file. To display the DNG (i.e. convert it into RGB), a lot of additional work is required (demosaic, many color transformations, processing opcodes). The DNG to RGB convertor would be probably much larger, than the UTIF.js library itself.
