### ISSUE TITLE
How to determine bits per channel?

### ISSUE THREAD

**Issue by photopaul25** [photopea/UTIF.js#55]
Is there a way to determine the pits per channel of a tif file?  For example I am thinking it would be nice to have something like `ifds[0].bitDepth` like UTIF has `ifds[0].width`.

**Comment by photopea** [comment]
TIFF files contain much more information, than just width, height and bits per channel, in so-called Tags (TIFF = Tagged Image File Format). Tags are numbers between 0 and 65535. I don't think it is right to define a "word" for each tag.

You can access Bits Per Sample using `ifds[0].t258[0]`  https://www.awaresystems.be/imaging/tiff/tifftags/bitspersample.html  . Tag 277 is also related to it (samples per pixel) https://www.awaresystems.be/imaging/tiff/tifftags/samplesperpixel.html

**Comment by photopaul25** [comment]
That works for me, thank you for the quick reply! 

I wonder if it would be worth making like a UTIF_Meta library where you can pass and ifd and it would build out a more user friendly property list for common fields, such as camera manufacture, and camera lens.

**Comment by photopea** [comment]
I already have such database of tag numbers and string names, I use it for debug purposes (to quickly see, what data are available in a TIFF file).

I think you never need to print all TIFF tags in practice. You usually want to extract one or more specific tags, and it is easier to refer to them with a number in your code (it is also shorter).
