### ISSUE TITLE
Wrong documentation description of decodeImage from 3.0.0

### ISSUE THREAD

**Issue by massic80** [photopea/UTIF.js#56]
Hi,
I noticed that you just released version 3.0.0 on npm, where decodeImages becomes decodeImage.
The problem is: the fingerprint of the function changes
UTIF.decodeImages = function(buff, ifds) // 2.0.1
UTIF.decodeImage = function(buff, img, ifds) // 3.0.0

but the documentation doesn't cite it. I just created a pull request on [@types/utif](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/utif/index.d.ts) in order to help Typescript users and I just guessed the second parameter's description with _* param img the image file directory to be decoded_ but I'd love a complete description the readme.md here :)

**Comment by photopea** [comment]
Hi, we only maintain the Javascript version here on GitHub. The description of UTIF.decodeImage() is here on GitHub, too.

Our fans made some NPM and TypeScript versions @Scimonster  :) maybe you should ask them.

**Comment by massic80** [comment]
Hi @photopea ,
I know you _only maintain the Javascript version here on GitHub_, but [your documentation](https://github.com/photopea/UTIF.js) says that

#### `UTIF.decodeImage(buffer, ifd)`
* `buffer`: ArrayBuffer containing TIFF or EXIF data
* `ifd`: the element of the output of UTIF.decode()
* If there is an image inside the IFD, it is decoded and three new properties are added to the IFD:
* * `width`: the width of the image
* * `height`: the height of the image
* * `data`: decompressed pixel data of the image

which is different than your definition at https://github.com/photopea/UTIF.js/blob/master/UTIF.js#L101

**Comment by photopea** [comment]
Do you mean the third parameter? It is there only to decode some raw Nikon files (.NEF). The README would probably be 2x longer, if I had to explain it.

It is never needed for TIFFs. You should call it with two parameters only.

**Comment by massic80** [comment]
Ah OK, thank you.
I figured out that the new parameter was the second, since `decodeImages` had an array as parameter.
Turns out it is the third :)
Moving on to update the pull request ;)

**Comment by photopea** [comment]
TIFF files can contain many images, and users may want to decode just some of them (decoding all may take significantly more time and memory).

The old decodeImages() decoded all present images, but with decodeImage() you can decode only images that you need :)

E.g. RAW images contain both RAW and JPG versions of the image. In Photopea, the decodeImage() allows us to decode RAW only (skip decoding JPG) and open the RAW image faster :)

**Comment by johnthad** [comment]
> Do you mean the third parameter? It is there only to decode some raw Nikon files (.NEF). The README would probably be 2x longer, if I had to explain it.
> 
> It is never needed for TIFFs. You should call it with two parameters only.

In `UTIF.decodeImage = function(buff, img, ifds)`, what do I pass as `img`? In the particular use case I'm looking at now, I have a small TIFF in Base64 inside an XML file. Previously my call looked like:

```
const arrBuff = this._base64ToArrayBuffer(base64);
const ifds = UTIF.decode(arrBuff);
UTIF.decodeImages(arrBuff, ifds);
``` 

What should I pass for `UTIF.decodeImage = function(buff, img, ifds)`?

If I get something working, I'd be happy to make a PR for the README.md.

**Comment by photopea** [comment]
@johnthad I believe it is all documented in the README. There is even a sample of code. Please, look at README and tell me, what exactly is not clear.

**Comment by johnthad** [comment]
I did look. The `master` README.md is "a month ago" and has only `UTIF.decodeImage(buffer, ifd)`, _not_ `UTIF.decodeImage = function(buff, img, ifds)`.

Looking closer, it seems that the example`console.log(ifds[0].width, ifds[0].height, ifds[0]);` is better written as `console.log(ifds[0]['t256'][0], ifds[0]['t257'][0], ifds[0]);`

Now `var rgba  = UTIF.toRGBA8(ifds[0]);` gives me an empty `Uint8Array`:

![screen shot 2019-02-15 at 04 36 42](https://user-images.githubusercontent.com/5176962/52847866-5f847c80-30db-11e9-94a1-749f36ffe809.png)

So what gets me `rgba` such that I can create a canvas?

```
const canvas = document.createElement('canvas');
canvas.width = ifds[0]['t256'][0];
canvas.height = ifds[0]['t257'][0];
const ctx = canvas.getContext('2d');
const imageData = ctx.createImageData(canvas.width, canvas.height);
for (let i = 0; i < rgba.length; i++) {
  imageData.data[i] = rgba[i];
}
ctx.putImageData(imageData, 0, 0);
imageSrc = canvas.toDataURL();
```

**Comment by photopea** [comment]
You should ignore the third parameter of UTIF.decodeImage. Call it with two parameters, as the docs says.

The "width" and "height" are new redundant properties, added by decodeImage(). I believe they are more comfortable to use, than ['t256'][0].

It is hard to tell why toRGBA8() gives you an empty array :( could you share your TIFF image with us?

**Comment by johnthad** [comment]
Sorry, I saw my error, and my edit crossed your note. I was calling `UTIF.decodeImage(arrBuff, ifds);` vs. `UTIF.decodeImage(arrBuff, ifds[0]);` 

And using `pages` as the `var`|`const` makes it clearer in my head than `ifds`

**Comment by Koomita** [comment]
> You should ignore the third parameter of UTIF.decodeImage. Call it with two parameters, as the docs says.
> 
> The "width" and "height" are new redundant properties, added by decodeImage(). I believe they are more comfortable to use, than ['t256'][0].
> 
> It is hard to tell why toRGBA8() gives you an empty array :( could you share your TIFF image with us?

I got the same issue with `toRGBA8() gives you an empty array`, here is [the file](http://seikichi.github.io/tiff.js/images/palette-1c-8b.tiff)

**Comment by photopea** [comment]
@Koomita are you sure it gives you an empty array just for this file, and not for other TIFF files?

**Comment by Koomita** [comment]
> @Koomita are you sure it gives you an empty array just for this file, and not for other TIFF files?

no, for all TIFF files I've got.

here is the code:

```
const fileBuffer = await file.arrayBuffer();
      const ifds = UTIF.decode(fileBuffer);
      const [page] = ifds;
      UTIF.decodeImage(fileBuffer, ifds);
      const rgba = UTIF.toRGBA8(page);
```

**Comment by photopea** [comment]
Then, I think you are using the library the wrong way.  I don't know what this syntax means: "const [page] " - it is probably not javascript, so I can not help you :(

Read our main page to learn how to use UTIF.js

**Comment by johnthad** [comment]
If you are attempting to use Array destructuring to break out the individual IFDs for each image, you're missing the ellipsis, and then getting the RGBA from the wrong part. Instead of 

    const [page] = ifds;
    UTIF.decodeImage(fileBuffer, ifds);

try

    const [...page] = ifds;
    UTIF.decodeImage(fileBuffer, page[0]);

See [Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment).

> here is the code:
> 
> ```
> const fileBuffer = await file.arrayBuffer();
>       const ifds = UTIF.decode(fileBuffer);
>       const [page] = ifds;
>       UTIF.decodeImage(fileBuffer, ifds);
>       const rgba = UTIF.toRGBA8(page);
> ```

**Comment by massic80** [comment]
Hola guys, sorry for moving a bit OT (maybe you are, as well), but wasn't this supposed to stay on ES2015 #58 ? :)
I'm glad to see that something changed!
In case you'd desire to port it, just whistle! ;)

**Comment by massic80** [comment]
Hola guys, sorry for moving a bit OT (maybe you are, as well), but wasn't this supposed to stay on ES5 (#58) ? :)
I'm glad to see that something changed!
In case you'd desire to port it, just whistle! ;)

**Comment by Koomita** [comment]
> If you are attempting to use Array destructuring to break out the individual IFDs for each image, you're missing the ellipsis, and then getting the RGBA from the wrong part. Instead of
> 
> ```
> const [page] = ifds;
> UTIF.decodeImage(fileBuffer, ifds);
> ```
> 
> try
> 
> ```
> const [...page] = ifds;
> UTIF.decodeImage(fileBuffer, page[0]);
> ```
> 
> See [Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment).
> 
> > here is the code:
> > ```
> > const fileBuffer = await file.arrayBuffer();
> >       const ifds = UTIF.decode(fileBuffer);
> >       const [page] = ifds;
> >       UTIF.decodeImage(fileBuffer, ifds);
> >       const rgba = UTIF.toRGBA8(page);
> > ```

thanks, it works. turns out I mistakenly put the whole ifds data into the second argument's place😅
