### ISSUE TITLE
How about moving to ES6?

### ISSUE THREAD

**Issue by massic80** [photopea/UTIF.js#58]
Hi,
I just submitted a pull request and noticed that UTIF is written in plain old ES5.
Moving it to ES6 (and following) would make it more compact, readable, "splittable" (one could import just the module parts he needs) and, when no transpiling will be needed, more performant.
I could give my support on the transition :)

**Comment by johnthad** [comment]
I’ve used UTIF.js in a browser, but it required a bit of massaging. Maybe as part of creating an ES6 version would be something suitable for Node.js and browsers, or to output two modules, one for Node.js and one for the client side.

**Comment by photopea** [comment]
I should note, that I only write JS code, which directly works in current browsers, without any additional manual or automatic editing. 

I think that JS specifications are backwards-compatible, so my code should be ES6, too. Are there any specific syntactic features, that you would like to introduce?

**Comment by massic80** [comment]
There is nothing feasible in ES6 that is not feasible in ES5, but it's easier, quicker, more compact, more optimized, it natively supports classes and will be soon supported by all browsers (Microsoft will even transition Edge to Blink engine in a few months).
Meanwhile, there are lots of transpilers, but I can understand your comfort in not instantiating a transpiling stack :)
Sidenote: ES6 code can cohabit with ES5; you are not forced to use classes, you could just begin with (a transpiler and) adding new features like fallback values (e.g. `replaceIMG(imgs=document.getElementsByTagName("img")`) {...}, `Array.includes`, `const` variables, etc.

**Comment by photopea** [comment]
"classes" in Javascript are just a syntactic sugar for prototype-based programming. I want this library consist only of "static" functions, so it is easily rewritable to C or other languages. There is no need for classes / constructors / methods etc.

I prefer to use "var" always, instead of combining var/const/let. 

As far as I understand, ES6 modules are identified by files they are stored in. Is it possible to have one module in several files, or several modules in one file? I may want to have UTIF.js in several files locally, but have it as one file, when it is used on my website.

**Comment by massic80** [comment]
It's a long story (and the modules are just part of it): you can make modules and classes and inherit them.
It's too long to be written here.
Just a notice: yes, _"classes" in Javascript are just a syntactic sugar for prototype-based programming_, but classes in ES6 are NOT just syntactic sugar.
I try to quickly answer your last message: a module (in a file) can export several objects (classes, strings, functions, whatever), and another one can import only needed ones https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import. Of course, it may import on its own, hence you can build your application in different files (e.g. replaceIMG as a plugin). In general, the applications are then minified and exported as a single file.

**Comment by TomasHubelbauer** [comment]
The addition of a build system means higher barrier to entry for drive-by contributors and if it is just to be able to use ES6, I think there is no rush, eventually all the features will make it into the browsers and then we can use them all natively. There is certainly beauty to the no-build-system thing @photopea has going on here which I think would be a pity to lose just to be able to use some features which in time will make it to the browsers anyway.

**Comment by johnthad** [comment]
> I should note, that I only write JS code, which directly works in current browsers, without any additional manual or automatic editing.

Doh! I see what I was doing wrong. Thanks.

**Comment by photopea** [comment]
I would like to keep using my current ES5.
