### ISSUE TITLE
WebWorker

### ISSUE THREAD

**Issue by rogersgj** [photopea/UTIF.js#6]
Any thoughts on how I could make this into a web worker?  I have everything but that part working.  With large documents, it would be great to have the multithreading.

**Comment by photopea** [comment]
Are you having problems with speed? I don't have any experience with multithreading in JS.

**Comment by rogersgj** [comment]
Yes.  I deal with very large documents at times, tiff images with 80 pages or more.  And when you open a document like that, there is a long wait time.  It would be great to be able to start viewing once the first image was processed.  I did rework it to use a web worker, but I cannot get e.target.response to work in the web worker.

**Comment by photopea** [comment]
Oh, I understand, that it is ugly, when your whole webapp freezes.

Send me some of your 80 page TIFFs, maybe I can find a bottleneck and make it a little (or a lot) faster.

**Comment by photopea** [comment]
I guess you have solved it. Let me know if you have any other questions.
