### ISSUE TITLE
Support for Multi-page?

### ISSUE THREAD

**Issue by payitforwardnow** [photopea/UTIF.js#61]
Support for multi-page tif? Maybe I missed it.

**Comment by photopea** [comment]
Hi, do you mean reading multiple images, that are stored in a TIFF file? It should work already. UTIF.decode() returns an array of IFDs ("pages"). You can call UTIF.decodeImage() on each IFD.

**Comment by shahareldad** [comment]
Any complete code sample to view all images?

Thanks

**Comment by photopea** [comment]
What do you mean? You can use TIFF URL inside <img> and call UTIF.replaceIMG() afterwards.

**Comment by johnthad** [comment]
You can try my example: https://github.com/johnthad/utif-demo/blob/master/thumbnails.html  This opens a 13 page TIFF, and loads each image.

The full repo has the two TIFFs I used. Also note that UTIF.replaceIMG() has been changed since my replaceIMG() examples.

**Comment by shahareldad** [comment]
Your example here is what I was missing, which is the understanding how to work with the canvas to load the images.

Thanks
