### ISSUE TITLE
A Clearer replaceIMG()

### ISSUE THREAD

**Issue by johnthad** [photopea/UTIF.js#62]
If you're dealing with TIFFs that must be scaled down to fit their allotted areas, an Image will scale more attractively than a Canvas. To use an image, replace lines 1079-81 of UTIF.js 

```
  var attr = ["style","class","id"];
  for(var i=0; i<attr.length; i++) cnv.setAttribute(attr[i], img.getAttribute(attr[i]));
  img.parentNode.replaceChild(cnv,img);
```
with the single line
```
  img.src = cnv.toDataURL('image/png');
```

The attached images show screen captures from a portion of a Group IV 300dpi Letter sized image when reduced to approximately one third its normal style. The left hand side shows the Canvas scaled; the right hand side shows the Image scaled.

![screen shot 2019-02-21 at 08 29 54](https://user-images.githubusercontent.com/5176962/53173143-0e7df800-35b5-11e9-9feb-d185dc9e2452.png)
![screen shot 2019-02-21 at 08 30 20](https://user-images.githubusercontent.com/5176962/53173153-12117f00-35b5-11e9-9e0e-e425bbd3a719.png)

**Comment by photopea** [comment]
Converting the canvas content into a PNG and then into a base64 string (done by toDataURL()) will certainly take some extra time and memory, so the whole rendering process could be a bit slower.

But this scaling issue is really interesting. Does it work this way in all browsers? Could we set some parameter of the canvas to make the scaling smoother, as the IMG is?

**Comment by johnthad** [comment]
Using Image improves scaling on Chrome, Firefox, and (testing through VirtualBox) Edge. Safari looks good with either Canvas or Image. IE9 and IE11 (again, using VirtualBox) looks poor with either Canvas or Image.

I admit this not a likely case. If a person is using UTIF.replaceIMG(), they likely have TIFFs in the desired size, and otherwise value speed over clarity. It may also be that those who deal in Letter and Legal size documents like my sample are more apt to be opening TIFFs in an application, and will not be using replaceIMG(). I don't see a noticeable difference in speed, and in any case, clarity is paramount for my application. Maybe this contrast between Image and Canvas is better noted in the README and this case closed.

**Comment by photopea** [comment]
Hi, I was thinking about it, and I really do like this idea with replacing the URI. It does take a bit more time and memory (350 ms extra time for 16 MPx image), but it makes everything cleaner. Only the "src" attribute of the image is replaced, so we don't replace actual elements, etc.

**Comment by photopea** [comment]
BTW. it is implemented here now.
