### ISSUE TITLE
UTIF only extracts preview of DNG

### ISSUE THREAD

**Issue by severussnape357** [photopea/UTIF.js#64]
`const fs = require('fs');
const UTIF = require('utif');
const UPNG = require('upng-js');
var buffer = fs.readFileSync('./test.dng');

//let tiffFile1 = UTIF.decodeImage(buffer, UTIF.decode(buffer));
imgLoaded(buffer);

function imgLoaded(e) {
    var ifds = UTIF.decode(e);
    UTIF.decodeImage(e, ifds[0])
    var rgba = UTIF.toRGBA8(ifds[0]); // Uint8Array with RGBA pixels
    var png = UPNG.encode([rgba.buffer], ifds[0].width, ifds[0].height, 0);
    //var tif = UTIF.encode([rgba.buffer], ifds[0].width, ifds[0].height, "");

    all = fs.createWriteStream("out." + "png");

    var buffer = new Buffer(png);
    all.write(buffer);

    all.end();

    //fs.writeFileSync('test.png', png);

}`

this only exports the preview? file of the dng; its is pretty small compared to the original; i tried to open it in photopea and it just worked fine; i could zoom all the way in etc; i downloaded it from photopea and it was the original size; how am i getting this to work with UTIF; or how do you do it on photopea;

**Comment by photopea** [comment]
Hi, this library only decodes the raw sensor data out of raw files. It is quite complex to convert such data into displayable "RGBA" (you need to do demosaicing, color space conversions, etc), it is out of scope of this library.

Photopea has its own non-opensource code to process raw photo data.
