### ISSUE TITLE
UTIF.toRGBA8 returns Uint8Array instead of Uint8ClampedArray

### ISSUE THREAD

**Issue by wouldntsavezion** [photopea/UTIF.js#65]
It's a very simple fix to change the type of the[ `img` variable](https://github.com/photopea/UTIF.js/blob/master/UTIF.js#L986) to Uint8ClampedArray as I don't think it should ever **not** be clamped (If I understood the code correctly).

Also, the [Readme does state that the return of `toRGBA8` is `ready to use in context2d.putImageData() etc.`](https://github.com/photopea/UTIF.js/blob/master/README.md#utiftorgba8ifd), which is not true as [`putImageData`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData#Parameters) requires an [`ImageData` object whose constructor only accepts clamped arrays.](https://developer.mozilla.org/en-US/docs/Web/API/ImageData#Constructors)

I decided to convert from Uint8Array to Uint8ClampedArray but it's obviously really slow, so a fix would be appreciated.

Edit: [Created a pull request.](https://github.com/photopea/UTIF.js/pull/66)

**Comment by photopea** [comment]
You can create a clamped array on the same ArrayBuffer this way:

    var clamped = new Uint8ClampedArray( UTIF.toRGBA8(...).buffer );

I dont like clamped arrays, as they require boundary checking, when you write to them (so writing to them could be a little slower than Uint8Array).

Also, ImageData.data is read-only property. You can not set ImageData.data = array from UTIF.toRGBA8().

**Comment by wouldntsavezion** [comment]
My point was that (again if I understood the toRGBA8 correctly), it shouldn't ever go out of bounds. So checking is kind of unnecessary. 

With your example, you still end up creating two arrays so if there's really no need for extra checks, it's definitely slower every time.

**Comment by photopea** [comment]
In my example, you don't create two arrays. You careate two ArrayBufferViews on the same ArrayBuffer. So it is slower only by a constant step - creating a viewer.

Why exactly do you "like" Clamped array more than a regular array? :D

**Comment by wouldntsavezion** [comment]
I thought that might be the case, it's not that bad then. I just think it makes more sense to use clamped arrays when working with RGB colors. 

Anyway thanks for clearing it up. I'll be using UTIF to manage textures for 3D models!
