### ISSUE TITLE
I'm unable to re-encode the decoded image (unknown type of tag: 254)

### ISSUE THREAD

**Issue by andormade** [photopea/UTIF.js#68]
The TIFF image I'm trying to decode and then re-encode is a 16bit grayscale raw image from a scanner.

I have a code simple as this:

```
const UTIF = require('utif');
const fs = require('fs');

const imageData = fs.readFileSync('image.tif');

const ifds = UTIF.decode(imageData);
UTIF.encode(ifds);
```

It throws me the this error:

```
Error: unknown type of tag: 254
    at Object.UTIF._writeIFD (/Users/andormade/git2/tiff-invert/node_modules/utif/UTIF.js:877:84)
    at Object.UTIF.encode (/Users/andormade/git2/tiff-invert/node_modules/utif/UTIF.js:74:20)
```

I wasn't able to attach the TIFF file, because it's too big, but you can download it from this link: https://www.dropbox.com/s/tyfro4ybwqd2x14/image.tif

**Comment by photopea** [comment]
Hi, UTIF.encode() is more like a nexperimental feature for encoding EXIF files. To encode images, use UTIF.encodeImage().

This library only supports basic TIFF encoding. We would like to encourage people to use PNG and other formats instead of TIFF.
