### ISSUE TITLE
多页tif只显示第一页

### ISSUE THREAD

**Issue by jyfei903** [photopea/UTIF.js#69]
多页tif只显示第一页
UTIF._imgLoaded = function(e){
嵌套for循环 i 名重复导致，重新修改嵌套for循环 i 改为 l 
}

**Comment by lkShi** [comment]
你好 大佬 没找到怎么改 没有嵌套for循环，但是

**Comment by photopea** [comment]
This is only a basic feature. In your website, you can have 

    UTIF._imgLoaded = function(e) { ....  }  

to re-define the UTIFs function (before it is executed). You can customize it in any way you want.
