### ISSUE TITLE
encodeImage TIFF with compression G4 not work

### ISSUE THREAD

**Issue by luanltt** [photopea/UTIF.js#70]
Hi,

I'm encountering this issue encodeImage TIFF with compression G4 not work.
Could you please check it?

```js
UTIF.encodeImage(
            rgba,
            width,
            height,
            { t259: [4] }
          )
```

Thank you very much!

**Comment by photopea** [comment]
Hi, this library is mainly for reading TIFFs. Our simple TIFF writer saves data as 8-bit RGBA without any compression, even if you specify it as a tiff tag..

I would like to suggest you to store your image as PNG instead. It may be 2x larger than G4, but it will work everywhere.
