### ISSUE TITLE
Split multi-page Tiff

### ISSUE THREAD

**Issue by tl24** [photopea/UTIF.js#72]
Is it possible to split a multi-page tiff into multiple images?  Either single-page tiffs or png/jpg, with png or jpg being preferred.  I see that decode returns an array of IFDs, but what can I do with that? Can each one be saved to a file as it's own tiff file, or do I need to call something else to make it an actual tiff file.  Or if it can be converted to png or jpg how is that done?

**Comment by photopea** [comment]
UTIF.js allows you to get pixel data out of a TIFF file (red, green and blue value for each pixel).

You will have to encode these data into JPG or PNG. The simplest way is probably to draw it into Canvas. In a browser, when you right-click the canvas, you can save the content as an image to your computer.

**Comment by photopea** [comment]
I will close it now.
