### ISSUE TITLE
can we use this library to compile a tiff from multiple sources?

### ISSUE THREAD

**Issue by alexgman** [photopea/UTIF.js#73]
I have files like png, gif, jpeg, pdf, and I need to be able to compile all of these into 1 tiff file. Can we use this library to do that?

**Comment by johnthad** [comment]
It [seems to](https://github.com/photopea/UTIF.js#encoding-tiff-images) but I've not tried it.

**Comment by photopea** [comment]
Hi, PDF is a vector format, TIFF does not support vector graphics.

GIF may be an animation. TIFF can store multiple images in one file, but TIFF viewers can not play them as animations.

What is the purpose of this? What about putting them all into one ZIP file, instead of one TIFF?

**Comment by photopea** [comment]
I will close it now.
