### ISSUE TITLE
problem encoding tiff with multiple pages

### ISSUE THREAD

**Issue by spsolutionsmexico** [photopea/UTIF.js#78]
Hello, I have used the library before, there is the problem that when I process a tif with multiple pages for conversion to png, it saves all the pages in the same image.
Original:
![110203400461](https://user-images.githubusercontent.com/31898562/68053430-7ee72800-fcb1-11e9-8d89-ea2ffb130d0c.png)

PNG file:
![cbimage](https://user-images.githubusercontent.com/31898562/68052585-8e657180-fcaf-11e9-94ad-55dcf920cbf7.jpg)

And my code is:
imagen_c is a base 64 tif
function(imagen_c){
        var ifds = UTIF.decode(_base64ToArrayBuffer(imagen_c));
        var decoded = UTIF.decodeImage(_base64ToArrayBuffer(imagen_c), ifds[0])
        console.log(ifds)
        var rgba = UTIF.toRGBA8(ifds[0]);
        var width = ifds[0].width;
        var height = ifds[0].height;
        var data = ifds[0].data;
        const png = new PNG({ width, height });
        png.data = data;
        var image_converted = PNG.sync.write(png);
       return image_converted.toString('base64');
}

function _base64ToArrayBuffer(base64) {
    var binary_string = atob(base64);
    var len = binary_string.length;
    var bytes = new Uint8Array(len);
    for (var i = 0; i < len; i++) {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
}

**Comment by photopea** [comment]
Hi, sorry, I never read the code of other people :(

Are you converting TIFF to PNG? "Encoding TIFF" - in your title - actually means converting an image into a TIFF format.

Can you share your TIFF file with me first? Both of your images open as PNGs for me.

**Comment by spsolutionsmexico** [comment]
Is it possible to do it privately? In fact I am trying to convert a tiff to png, the result is the image that I put in my first comment.

**Comment by photopea** [comment]
Send me your image to support@photopea.com

**Comment by photopea** [comment]
I believe "pngjs" expects the data in 4 bytes per pixel (1 byte for Red, 1 byte for Green, 1 byte for Blue, 1 byte for Alpha) - I call it RGBA8. 

But the uncompressed image data of a TIFF file (IFD.data) may have many different formats (e.g. 1 bit per pixel for black-and-white images). That is why UTIF.toRGBA8() was made - it extracts RGBA8 from any TIFF data.

Your TIFF image uses 1 bit per pixel, 1696 bits (212 bytes) per line. But "pngjs" expects 4 bytes per pixel, 4x1696=6784 Bytes per line (32x more). So it uses each 32 lines of a black-and-white image as one line of RGBA8 (colored) image. That is why you see 32 copies.
