### ISSUE TITLE
Both API and website doesn't decode the image correct

### ISSUE THREAD

**Issue by markb-trustifi** [photopea/UTIF.js#79]
This is the original image [w21.tiff.zip](https://github.com/photopea/UTIF.js/files/4013940/w21.tiff.zip):
![w21](https://user-images.githubusercontent.com/29097494/71640376-62577400-2c91-11ea-9de1-17e838e16426.png)

and this is decoded version by API and website:
![Screen Shot 2020-01-01 at 12 18 54](https://user-images.githubusercontent.com/29097494/71640355-f96ffc00-2c90-11ea-9c3b-17036942be0a.png)

**Comment by photopea** [comment]
Hi, I fixed it, it should work well now.

**Comment by markb-trustifi** [comment]
Thank you, it is working.
Now, there is a problem with different image - it is cropped and blurred.
![Screen Shot 2020-01-02 at 11 40 26](https://user-images.githubusercontent.com/29097494/71660818-e6befb00-2d54-11ea-9932-eef176d17309.png)

The original image: [check4.tiff.zip](https://github.com/photopea/UTIF.js/files/4015444/check4.tiff.zip)

**Comment by photopea** [comment]
Fixed :)
