### ISSUE TITLE
Displaying tiff image of html file in Browser

### ISSUE THREAD

**Issue by mhammadpk** [photopea/UTIF.js#8]
Hi,

I want to display tiff images contained in local html file in a web browser. Please guide me about the following:

1. - How can I use your utility to show tiff images contained in html file?
2. - On which browser will it work such as chrome, firefox, ie etc
3. - Will it work on ubuntu platform?

I am attaching code which I tried to display a simple tiff image in html file. Please let me know about it.
[UTiff.zip](https://github.com/photopea/UTIF.js/files/945312/UTiff.zip)

**Comment by photopea** [comment]
Do you know any Javascript programming? If not, I guess I can make a utility, that will replace <img elements with canvases of TIFF files automatically.

It will work in all browsers and all operating systems.

**Comment by mhammadpk** [comment]
Hi photopea,

Thanks for your reply. It will really nice if you can make a utility which will replace <img elements with canvases of Tiff files automatically, as I have been out of touch for a long time in javascript. The code will be quite useful for all other people as well.

I have following tag used in html files saved in my local drive:

`<A HREF="/path/to/file/a.tiff"><IMG WIDTH=40 HEIGHT=40 SRC="/path/to/file/a.tiff"></A>
`
which I need to replace the <img tag with canvas in such a way that tiff images will be shown to browser after parsing and when I click the image, it will download me a tiff file from the browser.

Html files containing tiff file paths should be displayed locally without the use of any webserver. Please let me know about it.

**Comment by photopea** [comment]
JS environment should be able to read the raw data of your local file. I am afraid, that when you doubleclick the "index.html" in your computer and it opens in a browser, JS can not read local files (because of CORS - same origin policy).  The same problem would happen, if you tried to load a local text file etc.  You would have to use a local web server (which is a very simple thing, it can be a browser extension).

**Comment by photopea** [comment]
I have added the new function UTIF.replaceIMG, which will let you display TIFF images inside <img> elements. See the new documentation. Just call it like this:

<body onload="UTIF.replaceIMG()">  ...

**Comment by mhammadpk** [comment]
Thanks photopea a lot,

Although, your utility works fine with "Web Server for Chrome", but I donot like to use the webserver, because I need to first copy all those tiff images and other resources from local drives in a specified folder, which will be linked with web server. Secondly, as this application will be installed at user end, so user will need to perform some settings of webserver before opening up the file in a browser, which will not be recommended.

So, I would like to look for following options:

1. Is there any other solution, which works without webserver?
2. I donot have control over application. So, I would like to parse html files before loading to browser.
First, I will like to convert tiff images to 'jpg' format for visualizing by first identifying the paths mentioned in  <img src tags. Save them in local file. Then,  change <img src paths from 'tiff' to 'jpg' files.

For instance, current html file contains tags:
<A HREF="/path/to/file/a.tiff"><IMG WIDTH=40 HEIGHT=40 SRC="/path/to/file/a.tiff"></A>

utility will identify "/path/to/file/a.tiff" path from "SRC" tag. Then, convert the image by sending the instruction to systems software (imagemagick) in Ubuntu, and save it to the specified folder. 

After conversion, it should become
..................
<A HREF="/path/to/file/a.tiff"><IMG WIDTH=40 HEIGHT=40 SRC="/newpath/to/file/a.jpg"></A>
...................

Can you guide me in writing that script in java script?


Please let me know about your concerns.

**Comment by photopea** [comment]
We are getting away from the TIFF format and I am not sure if I understand your problem correctly.

The Web, in order to be transparent and secure, has quite limited capabilities in comparison to native apps of the past. E.g. it can not store files into user's device, or read files from a device. The web app, which is programmed with Javascript, can load files only through the HTTP protocol, which requires some HTTP server.

If you need to work with local files without any HTTP servers, you should use some different technology than the web.

**Comment by mhammadpk** [comment]
Hi photpea,

Thanks for your reply. I want to share my insights that when I open locally saved "index.html" file without the **webserver**, which is using UTIF.js file, it is successfully load the tiff images as well, after performing some operations.

Let's suppose, generated report "index.html" and "UTIF.js" file are located at path  "/home/user/GUI/report". "index.html" file has the following tag:

`<A HREF="/home/user/datasample/a.tiff"><IMG WIDTH=40 HEIGHT=40 SRC="/home/user/datasample/a.tiff"></A>
`
When I open "index.html" file, it will not display tiff images. 

In order to allow the UTIF.js to access the images, I have to do following operations:

1. Create folders like "home/user/datasample" in "/home/user/GUI/report" path and place all images from the path "/home/user/datasample" to "/home/user/GUI/report/home/user/datasample" locally.
2. Change a path as
`<A HREF="/home/user/datasample/a.tiff"><IMG WIDTH=40 HEIGHT=40 SRC="home/user/datasample/a.tiff"></A>`

Then, UTIF.js can get access of the images. 

Now, I need java script function which assists in mapping local drive in such a way that UTIF.js can get the access of locally saved images without the need of copying images from one folder to another.

Please let me know about your concerns.

**Comment by photopea** [comment]
I am used to make web apps, where everything is served over HTTP. The way your browser maps your local storage into URL addresses is beyond my understanding.

I would start a local web server to make things simpler. You usually can set, which directory should be the root of the web server, to serve files from it. Or maybe consider putting everything online (I still don't understand, if you are making it for yourself, or for more people).
