### ISSUE TITLE
Compression 'deflate' support

### ISSUE THREAD

**Issue by ChristHeinrich** [photopea/UTIF.js#84]
If you use the deflate-Compression, the whole document is black.

Example .tif with these tags:
deflate.tif:
SubFileType (1 Long): Page
ImageWidth (1 Long): 1654
ImageLength (1 Long): 2338
BitsPerSample (3 Short): 8, 8, 8
Compression (1 Short): Deflate
Photometric (1 Short): RGB
StripOffsets (293 Long): 2571, 2632, 2693, 2754, 2815, 2876, 2937,...
SamplesPerPixel (1 Short): 3
RowsPerStrip (1 Long): 8
StripByteCounts (293 Long): 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61,...
XResolution (1 Rational): 78,7723243815319
YResolution (1 Rational): 78,7404226656563
ResolutionUnit (1 Short): Centimeter

**Comment by photopea** [comment]
Hi, are you trying to parse a TIFF file with UTIF.js ? Can you share that file with us? Can you open it at www.Photopea.com ?

**Comment by ChristHeinrich** [comment]
Hi, same result on www.Photopea.com. 
Here is the zipped tif-file:
[deflateTif.zip](https://github.com/photopea/UTIF.js/files/5033292/deflateTif.zip)

**Comment by photopea** [comment]
I fixed it, thanks for reporting :) The new UTIF.js is here and also at www.Photopea.com
