### ISSUE TITLE
encodeImage does not work

### ISSUE THREAD

**Issue by akidee** [photopea/UTIF.js#86]
To test reading and writing, I load an uncompressed 16 bit RGBA TIFF:

	var buffer = fs.readFileSync(process.argv[2])
	, ifds = utif.decode(buffer)
	if (ifds.length === 0) throw new Error('No IFD in TIFF found')
		
	const img = ifds[0]
	utif.decodeImage(buffer, img)

Result:

    {
      t256: [ 4004 ],
      t257: [ 3001 ],
      t258: [ 16, 16, 16, 16 ],
      t259: [ 1 ],
      t262: [ 2 ],
      t266: [ 1 ],
      t273: [ 8 ],
      t274: [ 1 ],
      t277: [ 4 ],
      t278: [ 3001 ],
      t279: [ 96128032 ],
      t282: [ 150 ],
      t283: [ 150 ],
      t284: [ 1 ],
      t286: [ 0.07999999799765646 ],
      t287: [ 0.026666667085761826 ],
      t296: [ 2 ],
      t297: [ 0, 1 ],
      t318: [ 0.31270000322551933, 0.32899999602907337 ],
      t319: [
        0.6399999856110662,
        0.3300000129570253,
        0.3000000117579475,
        0.6000000237487256,
        0.15000000576255842,
        0.05999999844003469
      ],
      t338: [ 2 ],
      t34675: Uint8Array [
          0,   0,  12,  72,  76, 105, 110, 111,  2, 16,   0,   0,
        109, 110, 116, 114,  82,  71,  66,  32, 88, 89,  90,  32,
          7, 206,   0,   2,   0,   9,   0,   6,  0, 49,   0,   0,
         97,  99, 115, 112,  77,  83,  70,  84,  0,  0,   0,   0,
         73,  69,  67,  32, 115,  82,  71,  66,  0,  0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  0,  0, 246, 214,
          0,   1,   0,   0,   0,   0, 211,  45, 72, 80,  32,  32,
          0,   0,   0,   0,   0,   0,   0,   0,  0,  0,   0,   0,
          0,   0,   0,   0,
        ... 3044 more items
      ],
      isLE: true,
      width: 4004,
      height: 3001,
      data: Uint8Array [
        112,  9,   0,   0,   0, 0, 255, 255,  81, 12,  78,   0,
         13,  0, 255, 255, 147, 2, 118,   6, 224,  2, 255, 255,
         13,  0,  85,   3, 121, 2, 255, 255,   0,  0,   0,   0,
          0,  0, 255, 255, 222, 1,  54,   1, 186,  2, 255, 255,
         81, 12, 139,   4, 226, 8, 255, 255,   0,  0,   0,   0,
        145,  1, 255, 255,   0, 0,   0,   0,   0,  0, 255, 255,
          0,  0, 228,   9, 168, 0, 255, 255,   0,  0, 161,  24,
         44, 15, 255, 255, 103, 0, 165,   4, 235,  1, 255, 255,
        228,  9, 115,   5,
        ... 96127932 more items
      ]
    }

Now I want to save the same image into another file. Just passing the decoded IFD will not work:

    buffer = utif.encodeImage(img.data, img.width, img.height, img)

Result:

    Error: unknown type of tag: 266

Now I make sure that only the required tags (TIFF spec, section 6) are passed as 4th argument. I copy them from the decoded IFD, because I have not changed any data:

	const NEEDED_TAGS = [ 262, 259, 257, 256, 296, 282, 283, 258, 277, 278, 273, 279 ]
	const ifdOut = {}
	NEEDED_TAGS.forEach(v => ifdOut['t'+v] = img['t'+v])

	console.log(ifdOut)

	// Will not accept unsupported (while in TIFF 6 documented) tags.
	var b = utif.encodeImage(img.data, img.width, img.height, ifdOut)
	console.log(b)
	fs.writeFileSync(process.argv[2]+'.neu.tif', Buffer.from(b))

Result:

    {
      t262: [ 2 ],
      t259: [ 1 ],
      t257: [ 3001 ],
      t256: [ 4004 ],
      t296: [ 2 ],
      t282: [ 150 ],
      t283: [ 150 ],
      t258: [ 16, 16, 16 ],
      t277: [ 3 ],
      t278: [ 3001 ],
      t273: [ 8 ],
      t279: [ 72096024 ]
    }
    ArrayBuffer {
      [Uint8Contents]: <4d 4d 00 2a 00 00 00 08 00 11 01 00 00 03 00 00 00 01 0f a4 00 00 01 01 00 03 00 00 00 01 0b b9 00 00 01 02 00 03 00 00 00 03 00 00 00 da 01 03 00 03 00 00 00 01 00 01 00 00 01 06 00 03 00 00 00 01 00 02 00 00 01 11 00 04 00 00 00 01 00 00 00 08 01 15 00 03 00 00 00 01 00 03 00 00 01 16 00 04 00 00 ... 48064916 more bytes>,
      byteLength: 48065016
    }

- For given dimensions, samples/px and bits/sample, the array buffer has the wrong length. Probably utif reduces depth to 8 bit?
- The resulting file cannot be read.

How can I save 16 bit RGBA files and what is exact format (given as IFD object) that utif accepts?

**Comment by photopea** [comment]
Hi, are you using the latest UTIF.js from here? Do not use a npm version, as it is very old.

**Comment by akidee** [comment]
I used the NPM version.
Now I have downloaded the master version from here, installed its dependencies and uninstalled the NPM version. Same problem with the size of the returned buffer and the TIFF file I cannot open in Mac OS.

**Comment by photopea** [comment]
In encodeImage(), the first parameter is the RGBA8 data. You can obtain RGBA8 data by calling UTIF.toRGBA8(...); 

You can not create 16-bit TIFF files with UTIF.js at the moment. If you are really serious about images, use the PNG format instead of TIFF. You can use our UPNG library.

**Comment by akidee** [comment]
OK, I understand. You should make clearer that the rgba must be RGBA8 data. I need support for 16 bit data. I am already creating an implementation based on this code: https://cdn.jsdelivr.net/npm/@bt-imaging/tiff@1.0.1/tiff.js
I will post my implementation as soon as possible.
