### ISSUE TITLE
Unminify blobs of code in UTIF.js

### ISSUE THREAD

**Issue by thany** [photopea/UTIF.js#89]
There are two big blobs of minified code in [UTIF.js](https://github.com/photopea/UTIF.js/blob/master/UTIF.js). Please unminify them.

If folks need minification in their projects, they will already have that set up. A library doesn't need to come minified, and especially shouldn't have minified code in its *source* code.

Minified code in sourcecode always looks and feels like trying to hide something. It's a common pattern for malicious code. Another disadvantage is that it's not humanly possible to fix bugs or make other changes. And even you are a wizard that can work in minified code, others can't. And a diff in an incoming PR will look absolutely terrible.

**Comment by photopea** [comment]
I do not want to release my Lossless JPEG decoder as open-source, I can offer it only as obfuscated code (as a "black box").

I believe the minified parts will never need to be changed, and we can use them as black boxes. Since UTIF.js is just one long file, having these minified parts helps navigating in it.

**Comment by thany** [comment]
> I do not want to release my Lossless JPEG decoder as open-source, I can offer it only as obfuscated code (as a "black box").

Then it should not be in source code like that. Please reference it by importing a file that is minified, and marked as such. So a minifier can take that into account, and can choose not to minify minified code.

> I believe the minified parts will never need to be changed

You know that is not true.

> Since UTIF.js is just one long file

There's no compelling reason, as far as I can tell, for it to be that way. One long file is almost always harder to navigate than a couple of smaller files, where a main/index imports them.

**Comment by photopea** [comment]
I really like when a library is just one JS file. It does not require multiple <script> tags, or concatenating JS files with some extra software.

I kow it is true that minified parts will never need to be changed.

I bleieve your minifier should be able to handle any valid javascript code. Whether the code is or is not minified is only a subjective opinion.

**Comment by thany** [comment]
One file is really only an advantage if you're literally copypasting the library into a project. But that's not how things work, generally speaking, given modern tooling such as webpack or what have you. If you really want to provide a download for a single file, for those who haven't grown out of using `<script>` tags, you can still do so.

But mind you, *source code* should be exactly that. Minified code is not sourcecode. 

> I bleieve your minifier should be able to handle any valid javascript code. 

While true, this is beyond the argument of including unverifyable minified code in the source code.

> Whether the code is or is not minified is only a subjective opinion.

That is not a very solid argument, unless you can find code where people disagree on whether it's minified code or source code. I bet you can't find such example.

**Comment by photopea** [comment]
This is my library and I decide what is the structure of my code :P

**Comment by thany** [comment]
Sure, it's all yours, mate. I'm only pointing out bad practice. Trying to be helpful.
This will bite you further down the line at one point. I've been there. Many times. So don't say I didn't warn you.

When you do split up your code properly, I'll be back to open an issue that just says "told you" 😄
