### ISSUE TITLE
uncompressed single band images lacking tag 259

### ISSUE THREAD

**Issue by jonathanlurie** [photopea/UTIF.js#9]
Hi there,
I have an uncompressed single-band float32 tiff that (apparently) lacks the tag 259 (compression tag). Reading the spec, this tag seems mandatory so I don't know why ImageJ does not write it. Anyway, I tried to fix it by adding a default value in UTIF.js. In the function UTIF.decode, replacing that:

```javascript
var cmpr = img["t259"][0];  delete img["t259"];
```
by that:
```javascript
var cmpr = 1;
if( "t259" in img ){
	cmpr = img["t259"][0];  delete img["t259"];
}
```

Though, the problem seems to be rather that UTIF does not play well with 32bits images. Do you have any plans to improve this point?

Jo.

**Comment by photopea** [comment]
Hi, I haven't come across float32  TIFF images. Are they in the specification?  It sounds like it is just an array of float values ... why do you call it a TIFF file?

There are many images on the internet, that have a TIFF extension, but are "almost TIFF". I am not sure if extending UTIF library to handle non-standard files is a right way to go.

**Comment by photopea** [comment]
So can you send your files to me? Can other programs open your files?

**Comment by photopea** [comment]
I have to close it because of lack of details.
