### ISSUE TITLE
UTIF.decodeImage not working

### ISSUE THREAD

**Issue by RhaldGian** [photopea/UTIF.js#90]
Hi everyone,
I'm trying to extract images & metadata from multipage tiff file. When I do UTIL.decode(tiff)  I'm getting the right response but when I call UTIL.decodeImage(tiff, response[0]) it returns undefined. please thank you.  I'm using 3.1.0 from npm thank you.

**Comment by photopea** [comment]
Hi, the UTIF.decodeImage() does not return anything. Please, read your manual to learn what it does: https://github.com/photopea/UTIF.js

Also, to be sure, use the latest version from here. It is hard to tell who published that NPM version, and when.

**Comment by RhaldGian** [comment]
Hi, thank you for your response, Is there a way for me to get the colorspace/resolution of image in tiff file using data array (Uint8Array) created by UTIF.decodeImage()?

**Comment by photopea** [comment]
Hi, you need to access specific TIFF tags, like "tXYZ", to find a resolution ("DPI"). The number of lines / columns is stored as "width" and "height" after calling UTIF.decodeImage();

If you need to render the image, use UTIF.toRGBA8(), which will convert the data into RGBA8 format. It is all described in our manual.
