### ISSUE TITLE
 not support LZW ?

### ISSUE THREAD

**Issue by 1456118242** [photopea/UTIF.js#91]
When I render the tiff in LZW format, it is a black canvas. Below is my LZW tiff file. Please help me to see it.
[tif.zip](https://github.com/photopea/UTIF.js/files/5728408/tif.zip)

**Comment by 1456118242** [comment]
@syvaidya

**Comment by 1456118242** [comment]
@photopea

**Comment by 1456118242** [comment]
@syvaidya @photopea I use <a href="https://github.com/seikichi/tiff.js"> tiff </a> solved this problem 。I hope he is useful to you

**Comment by photopea** [comment]
Hi, I am very sorry, there really was a bug and it is fixed now. Thanks for sharing your file!
