### ISSUE TITLE
decode & decodeImage return the embedded thumbnail

### ISSUE THREAD

**Issue by thany** [photopea/UTIF.js#93]
`decode()` returns a single IFD, which is the embedded thumbnail. The full size image is definitely in there. XnView can view it,and Exiftool reports two "subfiles" (the first being the thumbnail). And indeed `decodeImage()` adds the width&height of the thumbnail, instead of the actual picture.

This is a DNG generated with Adobe DNG Converter, preserving embedded original RAWs. 

The actual image data appears to be in `t50740`, which is roughly the same size as the embedded original RAW, which is in `t50828`. I'm assuming these numbers are not random, and have some kind of meaning.

**Comment by photopea** [comment]
Hi, can you open your DNG in www.Photopea.com ? Do you see what you would expect?

**Comment by thany** [comment]
I sure do!

Btw I was wrong about `t50740`, I misread the lengh of that array. The data must be somewhere else.

**Comment by photopea** [comment]
DNG files often contain the raw image in the "subIFD" tag "t330" https://www.awaresystems.be/imaging/tiff/tifftags/subifds.html

Thanks to this tag, a TIFF file is not a linear list of IFDs, but more like a "tree" (your single IFD is just a root of that tree).

**Comment by thany** [comment]
I see, I found them. So can you explain how to read a DNG proper then? In other words, what does Photopea do to get to the full-res DNG picture? I imagine maybe it loops through the subIFDs and just grab the biggest one or something?

And does the full-res version in a DNG *always* sit in one of the subIFDs?

**Comment by photopea** [comment]
The content of DNG is described here: https://www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.4.0.0.pdf

Photopea loops through all IFDs (and sub-IFDs) and looks for the one with the biggest resolution. Usually, there is only one IFD. But sometimes, there are thumbnails (which are smaller). DNG files contain raw data from the Color Filter Array - https://en.wikipedia.org/wiki/Color_filter_array , one number per pixel.

So do not expect to get a RGB image out of a DNG file, like the one you see in Photopea or Photoshop, using only UTIF.js .

**Comment by photopea** [comment]
For RAW images, Photopea only decodes the raw sensor values into IFD.data. Try to play with that array. UTIF.toRGBA8() is not supported on raw photos.

Photopea contains about 30 kB of additional code to render a raw photo, it is not open-source.

**Comment by thany** [comment]
Ok but then why does UTIF claim to be able to read DNG, when the required CFA's are not being parsed?
Well I suppose *technically* it can read DNG, but not in a useful manner. Kind of like how I can read Spanish, but can't understand it.

**Comment by photopea** [comment]
it means reading the raw images from raw formats, not converting them to RGB.

**Comment by thany** [comment]
Okay fine. But can you at least make `UTIF.encode` work? When I feed it the biggest subIFD (whose `data` weight about 32MB after "decoding") what comes out is an `ArrayBuffer` of exactly 8 bytes, so basically everything is skipped.

It doesn't matter if I `decodeImage` this IFD or not.

Example:
```javascript
import UTIF from "utif";
import { promises as fs } from 'fs';

const buffer = await fs.readFile('gallery/filetypes/dng-with-embedded-raw.dng');
const ifds = UTIF.decode(buffer);
const biggestIFD = ifds[0].subIFD.reduce((previous, current) => current.t256[0] > previous.t256[0] ? current : previous, { t256: [0] });

UTIF.decodeImage(buffer, biggestIFD);
const outputBuffer = UTIF.encode(biggestIFD);
fs.writeFile('gallery/filetypes/dng-with-embedded-raw.tiff', Buffer.from(outputBuffer));

console.log(outbutBuffer);
```
This outputs to the console, and to a file, exactly the bytes `4d 4d 00 2a 00 00 00 08` and nothing more.

**Comment by photopea** [comment]
Please, read our manual: https://github.com/photopea/UTIF.js

The input of UTIF.encode() should be an array, not an object.

**Comment by photopea** [comment]
I guess it has been fixed.
