### ISSUE TITLE
New NPM Version Request

### ISSUE THREAD

**Issue by tsippert** [photopea/UTIF.js#94]
I was about to submit a pull request with some fixes, but I saw that it is already implemented here on Github
However the last changes are not available at NPM.

In NPM the last version is 3.1.0 from 2019-06-18: https://www.npmjs.com/package/utif
The last version bump was this one: https://github.com/photopea/UTIF.js/commit/27f1098a67c3cfd4348c9b8fd887fcd8cd171095

Could you please release a new version [**3.1.1 or 3.2.0]** so we can have the last updates via npm library?

**Comment by tsippert** [comment]
@Scimonster I just saw in this other closed issue https://github.com/photopea/UTIF.js/issues/13 that you are responsible to update the npm package, so I'm including you at the thread 😄

**Comment by photopea** [comment]
Feel free to upload UTIF.js to NPM yourself. I do not use NPM.
