### ISSUE TITLE
Downloading Tif files by using URL ?

### ISSUE THREAD

**Issue by u-uysal** [photopea/UTIF.js#95]
I have a URL (https://mminternalsadev.blob.core.windows.net/uploads/5ccad715074ce2b850f646d5-6710db20-210f-4453-941f-b50b671a7a3f?st=2021-03-12T12%3A23%3A46Z&se=2021-03-12T14%3A28%3A46Z&sp=r&sv=2018-03-28&sr=b&rsct=application%2Fpdf&sig=Gim0rLvibg42lonxUIaUrGA3XaXbBsKkhzdOdnnQPdc%3D). I want to download tif file by clicking the URL. How can I do that? This code works for PDF but not Tif

`<Flex direction="column">
        {upload.files?.map((file, index) => (
          <a
            key={`download_${index}`}
            download
            href={file.url}
            target="_blank"
            css={{ color: colors.primary[500], marginTop: '6px' }}
          >
            {file.name}
          </a>
        ))}
      </Flex>`

**Comment by photopea** [comment]
Hi, your URL seems to return a damaged PDF file.

I do not understand your code. I know only HTML and Javascript.
