### ISSUE TITLE
Lossless JPEG decoder only supports predictor modes 1, 6, and 7

### ISSUE THREAD

**Issue by SimonSegerblomRex** [photopea/UTIF.js#97]
Hi!

I noticed that the lossless JPEG decoder only supports predictor modes 1, 6, and 7. Can you add support for the rest?

Here are example files for predictor modes 0-7: [predictor-example-files.zip](https://github.com/photopea/UTIF.js/files/6315635/predictor-example-files.zip)

**Comment by photopea** [comment]
In all DNG files that I had, only predictors 1, 6 and 7 were used. So I thought there is no need to make a code longer, if the predictors are not used in practice :)

I implemented the missing ones. Thanks for providing DNG files! :)
