### ISSUE TITLE
UTIF.js error fix

### ISSUE THREAD

**Issue by programnara** [photopea/UTIF.js#98]
<pre>
[UTIF.js] fix :
line 1053 :
				if(false) {}
				else if(bps==1) mi=(data[dof+(x>>>3)]>>>(7-(x&7)))&1;
				else if(bps==4) mi=(data[dof+(x>>>1)]>>>(4-4*(x&1)))&15;
				else if(bps==8) mi= data[dof+x*smpls]; 
<hr>
add a line :
				else if(bps==2) mi=(data[dof+(x>>>2)]>>>(6-2*(x&3)))&3;
then it can show this tif :
https://www.eso.org/public/archives/images/original/eso9616a.tif
<hr>
for example [test.html]:

&lt;script type="text/javascript" src="UTIF.js"&gt;&lt;/script&gt;
&lt;body onload="UTIF.replaceIMG()"&gt;
&lt;img src="https://www.eso.org/public/archives/images/original/eso9616a.tif"&gt;
</pre>

**Comment by photopea** [comment]
Thanks, it is fixed now (in Photopea.com and here at Github). :)
