### ISSUE TITLE
TIFF partially drawn

### ISSUE THREAD

**Issue by Thierry58** [photopea/UTIF.js#99]
Hello
thank you for this package :-)
I am facing a strange issue: using UTIF in HTML page, a TIFF file is only partially displayed.
Actually the top left part of the tif is in the middle of the canvas.

When I open the tif in MS photo viewer:
![real](https://user-images.githubusercontent.com/84248292/118377418-686f9b80-b5cd-11eb-9e08-87706c3eca75.png)
What is drawn on the canvas:
![drawn](https://user-images.githubusercontent.com/84248292/118377413-60aff700-b5cd-11eb-903d-1ff0a301bc97.png)
No errors returned by UTIF.js, nothing in the console.
I tested several other TIFFs, it works like a charm but not this particular one.

The TIF file is read by java code and the resulting byte array is encoded as a Base64 string and passed to javascript.
My JS code in 2 functions:
```
loadTifFile = function(b64data) {
	viewer.decodedData = Base64Binary.decodeArrayBuffer(b64data);
	viewer.decodedIfds = UTIF.decode(viewer.decodedData);
	viewer.pageCount = viewer.decodedIfds.length;
	
	loadTifPage(0);
};
```
```
loadTifPage = function(imageNumber) {
	UTIF.decodeImage(viewer.decodedData, viewer.decodedIfds[imageNumber]);
	var rgba  = UTIF.toRGBA8(viewer.decodedIfds[imageNumber]);
	
	let imageData = new ImageData(viewer.pageOriginalWidth, viewer.pageOriginalHeight);
	for (let i = 0; i < rgba.length; i++) {
		imageData.data[i] = rgba[i];
	}
	viewer.contexts[imageNumber].putImageData(imageData, 0, 0);

	viewer.images[imageNumber] = new Image();
	viewer.images[imageNumber].src = viewer.canvases[imageNumber].toDataURL("image/png", 1);
	viewer.images[imageNumber].onload = function() {
		if (imageNumber == (viewer.pageCount - 1)) {
			draw();
		}
		else {
			loadTifPage(imageNumber + 1);
		}
	};
}
```
This is the TIF file zipped
[Document.zip](https://github.com/photopea/UTIF.js/files/6488176/Document.zip)

Could you please have a look and maybe find out why this happens ?
Is it possible that a dependency is missing or something.
Thank you a lot.

**Comment by johnthad** [comment]
The image seems fine (using tiffinfo from LIBTIFF 4.3.0):

    $ tiffinfo Document.TIFF
    TIFF Directory at offset 0x91874 (166e2)
      Subfile Type: multi-page document (2 = 0x2)
      Image Width: 2321 Image Length: 3408
      Resolution: 300.022, 299.971 pixels/inch
      Bits/Sample: 1
      Sample Format: unsigned integer
      Compression Scheme: LZW
      Photometric Interpretation: min-is-white
      Orientation: row 0 top, col 0 lhs
      Samples/Pixel: 1
      Rows/Strip: 28
      Planar Configuration: single image plane
      Page Number: 0-13
      DocumentName: C:\Users\e1064247\AppData\Local\Temp\3\gmXQzgHu
      Software: GraphicsMagick 1.3.31 2018-11-17 Q16 http://www.GraphicsMagick.org/
      ICC Profile: <present>, 2036 bytes

You shouldn't need to Base64 encode your TIFF. I send TIFF's from Java one page at a time as a raw byte array. On the JS side, I read the stream as a Uint8Array:

    const response = await fetch(this.imgurl, {
      method: 'GET',
      credentials: this._credentials,
    });
    if (response.ok) {
      // Display image.
      const imagebuf = await response.arrayBuffer();
      const magic = new Uint8Array(imagebuf.slice(0, 8));
      const imgType = this._getImageType(magic);
      if (imgType === 'tiff') {
        this._loadTiffImage(imagebuf);
      }
      ...

    // Load image data obtained from file
    _loadTiffImage(imagebuf) {
      const pages = UTIF.decode(imagebuf);
      UTIF.decodeImage(imagebuf, pages[0]);
      const rgba = UTIF.toRGBA8(pages[0]);    // Uint8Array with RGBA pixels
      if (rgba) {
        const canvas = document.createElement('canvas');
        canvas.width = pages[0].width;
        canvas.height = pages[0].height;
        if (pages[0].t282 && pages[0].t282[0]) {
          this._dpi = pages[0].t282[0][0] / pages[0].t282[0][1];
        } else {
          this._dpi = PDF_DPI;
        }
        const ctx = canvas.getContext('2d');
        this._imageData = ctx.createImageData(pages[0].width, pages[0].height);
        for (let i = 0; i < rgba.length; i++) {
          this._imageData.data[i] = rgba[i];
        }
        ctx.putImageData(this._imageData, 0, 0);

        // Convert canvas to img and add img to DOM.
        const image = this.shadowRoot.getElementById('image');
        image.src = canvas.toDataURL('image/png');
        this._dataMime = 'image/png';
      }
    }

Here's what I see reading your image as a file URL from disk.

![Screen Shot 2021-05-16 at 24 10 13 ](https://user-images.githubusercontent.com/5176962/118385250-817f4900-b5db-11eb-84c3-9e039a98a267.png)

**Comment by photopea** [comment]
I just inserted your TIFF into a webpage with the following code:

    <html>

    <head>  <script src="UTIF.js"></script>  </head>

    <body onload="UTIF.replaceIMG()">
    <img src="Document.TIFF" />
    </body>

    </html>

The image is displayed completely and correctly. However, it is quite large, so only a top left part can fit on my screen, I need to scroll a website to see the rest. Maybe that is your case, too?

Have you tried to convert your TIFF to a PNG and insert that PNG into a webpage? I think it would look the same.

**Comment by Thierry58** [comment]
Thank you for your answers both of you.  On the breach even on sundays ;-)

 @johnthad sadly, what you proposed is a no-go for me.
The image comes from another server, I don't load the file it-self, just receive a byte array instead.
So the java side has no concept of a page, I can only pass the whole thing to JS (slicing the string if it is too long).
For (too strong) security reasons, I may not write the file on the server, so I don't have any URL for the GET request.
Anyway, passing the file by URL is seen as security flaw by some tools such as blackduck, veraCode, others.. my customers are using :-(

The java code I did uses Eclipse RWT package, the HTML page is contained in a custom java object that only allows to pass strings to javascript, nothing else...
Encoding into a Base64 string might not be the best option, I am quite bad in javascript.
I wanted to avoid strings with special characters such as quotes.
And I thought JS had a good support for B64, maybe I was wrong.
Besides, I swear I tested many files, TIFF with UTIF but also PNG, JPEG, etc.. without it, and it seems to work fine. 
I can attach the whole javascript, yet I am not sure it would help without the java part...

I don't understand in the code you wrote, what is the use of this
`const magic = new Uint8Array(imagebuf.slice(0, 8))`
Looks like a good idea, but is this 'magic' variable provided to a function/process somewhere ?
I ask because what is provided to UTIF afterwards is the raw byte array, correct ?

Anyway, thank you for your time.

**Comment by Thierry58** [comment]
@photopea hello and thank you again for UTIF.js.
"replaceIMG()" looks good but I can't do this for the same HTML also displays non-tiff images.
Another thing, I need to have a "handle" on the image, so that zooming in/out and rotating is possible for the user.

Yes the TIFF is large indeed.
The canvas is set to have image width and height.
And for that particular tiff, all that appears on screen is that little screenshot (the second one) in the middle of the canvas.

**EDIT:**
I did not try to convert to PNG, but I tried using the URL instead of the array of bytes in another environment.
With the help of Visual Code, so no java, no Base64 this time.

These lines instead of the loadTifFile function in first comment.
```
var xhr = new XMLHttpRequest();
xhr.open("GET", tifURL);
xhr.responseType = "arraybuffer";
xhr.onload = function(e) {
  let decoded = UTIF.decode(e.target.response);
  viewer.pageCount = decoded.length;
  loadTifPage(e.target.response, 0, decoded);
};
xhr.send();
```
And yes, it works...
![TIFFbyURL](https://user-images.githubusercontent.com/84248292/118395333-1587f980-b64a-11eb-808c-b7c49268e34b.png)
I can not use that, but that means problem comes from the encoded string...

I installed UTIF through node.js / npm. Same for PAKO.
I can see UTIF is alone but PAKO has come with some dependencies in a lib folder.
There are also other sub-folders in the node modules and tbh I am not exactly sure what was installed by UTIF or PAKO...
Could it be the reason ? Do I need to provide it all to the HTML page ?

**Comment by johnthad** [comment]
> I don't understand in the code you wrote, what is the use of this
> `const magic = new Uint8Array(imagebuf.slice(0, 8))`
> Looks like a good idea, but is this 'magic' variable provided to a function/process somewhere ?
> I ask because what is provided to UTIF afterwards is the raw byte array, correct ?

I'm sorry, I misidentified that. Yes, I am sending the image to UTIF as a raw byte array. I should have removed the "magic" part. The repositories I deal with have a number of JPEG-in-TIFF images that use TIFF6. Not all of these are encoded the same way, and it's more reliable to extract the JPEG on the server in Java and send that. Also there are times that our user have replaced a TIFF image with another format, so go looking for a TIFF but find a PNG, PDF, etc. I've taken to checking the first few bytes for the image type so I can respond to images other than TIFF.

**Comment by johnthad** [comment]
> I installed UTIF through node.js / npm. Same for PAKO.
> I can see UTIF is alone but PAKO has come with some dependencies in a lib folder.
> There are also other sub-folders in the node modules and tbh I am not exactly sure what was installed by UTIF or PAKO...
> Could it be the reason ? Do I need to provide it all to the HTML page ?

All I had to do was add `<script src="./node_modules/utif/UTIF.js"></script>` to an HTML page (see https://github.com/johnthad/utif-demo/blob/master/thumbnails-lzw.html). With that I can extract all 13 pages of your image.

You might want to test what `Base64Binary.decodeArrayBuffer()` is returning.

**Comment by Thierry58** [comment]
Thank you for your help and time.
Not coding in JS for long, so I did mistakes with the canvas (i.e. changing its size) which has impacts on the image returned by `Canvas.toDataURL()`.
So UTIF is not the culprit, I am :(
Sorry for that.

I don't know if it was the right way, I closed this ticket.
Good day :-)
